-- =============================================================================
-- 4IBIB Supabase canonical schema
-- =============================================================================
-- Run this whole file in the Supabase SQL Editor. It nukes every object
-- under the public schema (tables, types, functions, policies) and rebuilds
-- the canonical shape from scratch, then applies the SEED block at the
-- bottom. The SEED block is regenerated by `npm run seed:schedule`.
--
-- Sections:
--   1. Reset
--   2. Extensions
--   3. Enum types
--   4. Tables
--   5. Functions
--   6. Indexes
--   7. Triggers
--   8. Row Level Security and policies
--   9. Schedule seed (auto-generated; do not edit between SEED markers)
-- =============================================================================
-- The whole script runs inside a single transaction so a failure rolls back
-- without leaving partial state behind.

begin;


-- =============================================================================
-- 1. Reset
-- =============================================================================
-- Drops every object the schema is about to recreate. Keeping this list
-- explicit (instead of `drop schema public cascade`) preserves Supabase's
-- default schema-level grants and any extension that might live in public.

drop view if exists public.volunteers cascade;

drop table if exists public.content_audit_log cascade;
drop table if exists public.prayer_request_rate_limits cascade;
drop table if exists public.prayer_requests cascade;
drop table if exists public.admin_rate_limit_buckets cascade;
drop table if exists public.member_relationships cascade;
drop table if exists public.members cascade;
drop table if exists public.households cascade;
drop table if exists public.volunteers cascade;
drop table if exists public.schedule_items cascade;
drop table if exists public.announcements cascade;
drop table if exists public.admin_users cascade;
drop table if exists public.recurring_meetings cascade;
drop table if exists public.ministries cascade;
drop table if exists public.church_profile cascade;

drop function if exists public.touch_updated_at() cascade;
drop function if exists public.log_content_audit() cascade;
drop function if exists public.is_admin() cascade;
drop function if exists public.is_owner() cascade;
drop function if exists public.upsert_ministry_id(text) cascade;
drop function if exists public.set_ministry_slug() cascade;
drop function if exists public.ministry_slug(text) cascade;
drop function if exists public.list_admins() cascade;
drop function if exists public.revert_audit_entry(uuid) cascade;
drop function if exists public.check_admin_rate_limit(text) cascade;
drop function if exists public.archive_member(uuid) cascade;
drop function if exists public.restore_member(uuid) cascade;
drop function if exists public.archive_announcement(uuid) cascade;
drop function if exists public.restore_announcement(uuid) cascade;
drop function if exists public.archive_schedule_item(uuid) cascade;
drop function if exists public.restore_schedule_item(uuid) cascade;
drop function if exists public.archive_prayer_request(uuid) cascade;
drop function if exists public.restore_prayer_request(uuid) cascade;
drop function if exists public.archive_ministry(uuid) cascade;
drop function if exists public.restore_ministry(uuid) cascade;
drop function if exists public.find_member_duplicates(text, text, text, text) cascade;
drop function if exists public.purge_old_prayers() cascade;
drop function if exists public.anonymize_member(uuid) cascade;

drop type if exists public.admin_role cascade;
drop type if exists public.announcement_category cascade;
drop type if exists public.announcement_status cascade;
drop type if exists public.schedule_status cascade;
drop type if exists public.prayer_status cascade;
drop type if exists public.marital_status cascade;
drop type if exists public.gender cascade;
drop type if exists public.membership_status cascade;
drop type if exists public.church_role cascade;
drop type if exists public.relationship_type cascade;


-- =============================================================================
-- 2. Extensions
-- =============================================================================

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;


-- =============================================================================
-- 3. Enum types
-- =============================================================================

create type public.admin_role as enum ('owner', 'editor');
create type public.announcement_category as enum ('geral', 'evento', 'juventude', 'oracao');
create type public.announcement_status as enum ('draft', 'scheduled', 'published', 'archived');
create type public.schedule_status as enum ('scheduled', 'suspended', 'free');
create type public.prayer_status as enum ('novo', 'em_oracao', 'concluido');
create type public.marital_status as enum ('solteiro', 'casado', 'viuvo', 'divorciado', 'uniao_estavel');
create type public.gender as enum ('masculino', 'feminino', 'outro');
create type public.membership_status as enum ('ativo', 'inativo', 'transferido', 'falecido');
create type public.church_role as enum ('membro_comum', 'presbitero', 'diacono', 'conselho_fiscal', 'tesoureiro', 'secretario', 'pastor', 'pastor_auxiliar');
create type public.relationship_type as enum ('conjuge', 'pai', 'mae', 'filho', 'irmao', 'avo', 'neto', 'tio', 'sobrinho', 'responsavel');


-- =============================================================================
-- 4. Tables
-- =============================================================================

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role public.admin_role not null,
  created_at timestamptz not null default now()
);

create table public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  summary text not null,
  category public.announcement_category not null,
  published_at timestamptz not null default now(),
  pinned boolean not null default false,
  cta_label text not null default '',
  cta_url text not null default '',
  status public.announcement_status not null default 'published',
  expires_at timestamptz null,
  image_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create table public.households (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  head_member_id uuid null,
  address_zip text not null default '',
  address_street text not null default '',
  address_number text not null default '',
  address_complement text not null default '',
  address_neighborhood text not null default '',
  address_city text not null default '',
  address_state text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create table public.members (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  preferred_name text not null default '',
  birth_date date null,
  marital_status public.marital_status null,
  gender public.gender null,
  photo_url text not null default '',
  email text not null default '',
  phone text not null default '',
  whatsapp text not null default '',
  cpf text null,
  rg text not null default '',
  rg_issuer text not null default '',
  profession text not null default '',
  address_zip text not null default '',
  address_street text not null default '',
  address_number text not null default '',
  address_complement text not null default '',
  address_neighborhood text not null default '',
  address_city text not null default '',
  address_state text not null default '',
  household_id uuid null references public.households(id) on delete set null,
  church_role public.church_role not null default 'membro_comum',
  membership_status public.membership_status not null default 'ativo',
  joined_at date null,
  baptism_date date null,
  baptism_location text not null default '',
  transferred_from text not null default '',
  emergency_contact_name text not null default '',
  emergency_contact_phone text not null default '',
  prayer_topics text[] not null default '{}',
  spiritual_gifts text[] not null default '{}',
  allergies text not null default '',
  medical_notes text not null default '',
  consent_medical_data_at timestamptz null,
  is_volunteer boolean not null default false,
  volunteer_ministries text[] not null default '{}',
  volunteer_unavailable_dates date[] not null default '{}',
  volunteer_notes text not null default '',
  notes text not null default '',
  consent_given_at timestamptz null,
  consent_version text not null default '',
  public_directory boolean not null default false,
  data_retention_until date null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  constraint members_cpf_format check (cpf ~ '^[0-9]{11}$' or cpf is null)
);

alter table public.households
  add constraint households_head_member_fk
  foreign key (head_member_id) references public.members(id) on delete set null;

create table public.member_relationships (
  id uuid primary key default gen_random_uuid(),
  from_member_id uuid not null references public.members(id) on delete cascade,
  to_member_id uuid not null references public.members(id) on delete cascade,
  type public.relationship_type not null,
  start_date date null,
  end_date date null,
  created_at timestamptz not null default now(),
  constraint member_relationships_different_members check (from_member_id <> to_member_id),
  constraint member_relationships_unique_active unique (from_member_id, to_member_id, type, start_date)
);

create table public.schedule_items (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  ministry text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  location text not null,
  summary text not null,
  preacher text not null default '',
  director text not null default '',
  sound_team text not null default '',
  passage text not null default '',
  occasion_label text not null default '',
  status public.schedule_status not null default 'scheduled',
  featured boolean not null default false,
  series_id uuid null,
  preacher_member_id uuid null references public.members(id) on delete set null,
  director_member_id uuid null references public.members(id) on delete set null,
  sound_member_id uuid null references public.members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  constraint schedule_time_order check (ends_at > starts_at),
  constraint schedule_items_starts_at_title_unique unique (starts_at, title)
);

create table public.prayer_requests (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contact text not null default '',
  message text not null,
  status public.prayer_status not null default 'novo',
  pastoral_notes text not null default '',
  assigned_to uuid null references public.admin_users(user_id) on delete set null,
  seen_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create table public.admin_rate_limit_buckets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  created_at timestamptz not null default now()
);

create table public.prayer_request_rate_limits (
  id uuid primary key default gen_random_uuid(),
  ip_hash text not null,
  created_at timestamptz not null default now()
);

create table public.content_audit_log (
  id uuid primary key default gen_random_uuid(),
  table_name text not null,
  row_id text not null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  changed_by uuid,
  changed_at timestamptz not null default now(),
  old_row jsonb,
  new_row jsonb
);

create table public.church_profile (
  id text primary key default 'main' check (id = 'main'),
  name text not null default '',
  short_name text not null default '',
  tagline text not null default '',
  city text not null default '',
  pastor_name text not null default '',
  address text not null default '',
  email text not null default '',
  whatsapp text not null default '',
  instagram_url text not null default '',
  youtube_url text not null default '',
  maps_url text not null default '',
  hero_verse text not null default '',
  mission text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ministries (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  summary text not null default '',
  meeting_time text not null default '',
  contact text not null default '',
  color text not null default '#0f766e',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create table public.recurring_meetings (
  id uuid primary key default gen_random_uuid(),
  profile_id text not null default 'main' references public.church_profile(id) on delete cascade,
  title text not null,
  weekday smallint not null check (weekday between 0 and 6),
  starts_at time not null,
  ends_at time not null,
  description text not null default '',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recurring_meeting_time_order check (ends_at > starts_at)
);

insert into public.church_profile (
  id, name, short_name, tagline, city, pastor_name, address, email, whatsapp,
  instagram_url, youtube_url, maps_url, hero_verse, mission
) values (
  'main',
  '4a Igreja Batista Independente Betel',
  '4a Betel',
  'Uma igreja para servir a cidade com Palavra, comunhao e cuidado.',
  'Caruaru, PE',
  'Pr. Samuel Costa',
  '478 Rua Jose Victor de Albuquerque',
  '4ibibetel@gmail.com',
  '+55 81 98122-0651',
  'https://www.instagram.com/4igrejabatista/',
  'https://www.youtube.com/@4aibibetel864',
  'https://maps.google.com/?q=Av.+Central,+420+-+Centro',
  'Assim brilhe a luz de voces diante dos homens, para que vejam as suas boas obras e glorifiquem o Pai de voces que esta nos ceus. - Mateus 5.16',
  'Cultivar discipulos de Jesus que servem com excelencia, oracao e acolhimento.'
) on conflict (id) do nothing;


-- =============================================================================
-- 5. Functions
-- =============================================================================

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.log_content_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_row jsonb;
  target_id text;
begin
  if tg_op = 'DELETE' then
    target_row = to_jsonb(old);
    target_id = old.id::text;
  else
    target_row = to_jsonb(new);
    target_id = new.id::text;
  end if;

  insert into public.content_audit_log (
    table_name, row_id, action, changed_by, old_row, new_row
  ) values (
    tg_table_name,
    target_id,
    tg_op,
    auth.uid(),
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then target_row else null end
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid() and role = 'owner'
  );
$$;

create or replace function public.list_admins()
returns table (
  user_id uuid,
  email text,
  display_name text,
  role public.admin_role,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado: apenas admins podem listar admins.';
  end if;

  return query
    select
      a.user_id,
      u.email::text,
      coalesce(u.raw_user_meta_data->>'name', '')::text as display_name,
      a.role,
      a.created_at
    from public.admin_users a
    inner join auth.users u on u.id = a.user_id;
end;
$$;

create or replace function public.revert_audit_entry(entry_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  entry public.content_audit_log%rowtype;
  allowed_tables text[] := array[
    'announcements',
    'schedule_items',
    'prayer_requests',
    'church_profile',
    'ministries',
    'recurring_meetings',
    'members',
    'households',
    'member_relationships'
  ];
  cols text;
  vals text;
  set_clause text;
  payload jsonb;
begin
  if not public.is_admin() then
    raise exception 'Acesso negado: apenas admins podem reverter alteracoes.';
  end if;

  select * into entry from public.content_audit_log where id = entry_id;
  if not found then
    raise exception 'Entrada de audit log nao encontrada: %', entry_id;
  end if;

  if not (entry.table_name = any(allowed_tables)) then
    raise exception 'Tabela nao autorizada para revert: %', entry.table_name;
  end if;

  if entry.action = 'INSERT' then
    execute format('delete from public.%I where id = $1', entry.table_name)
      using entry.row_id;
  elsif entry.action = 'UPDATE' then
    payload := entry.old_row;
    if payload is null then
      raise exception 'old_row ausente em UPDATE; impossivel reverter.';
    end if;
    select string_agg(format('%I = (jsonb_populate_record(null::public.%I, $1)).%I', key, entry.table_name, key), ', ')
      into set_clause
      from jsonb_object_keys(payload) as key
      where key <> 'id';
    if set_clause is null then
      return;
    end if;
    execute format(
      'update public.%I set %s where id = $2',
      entry.table_name,
      set_clause
    ) using payload, entry.row_id;
  elsif entry.action = 'DELETE' then
    payload := entry.old_row;
    if payload is null then
      raise exception 'old_row ausente em DELETE; impossivel reverter.';
    end if;
    select
      string_agg(format('%I', key), ', '),
      string_agg(format('(jsonb_populate_record(null::public.%I, $1)).%I', entry.table_name, key), ', ')
      into cols, vals
      from jsonb_object_keys(payload) as key;
    execute format(
      'insert into public.%I (%s) values (%s)',
      entry.table_name,
      cols,
      vals
    ) using payload;
  else
    raise exception 'Acao desconhecida: %', entry.action;
  end if;
end;
$$;

create or replace function public.check_admin_rate_limit(p_action text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  recent_count int;
begin
  if auth.uid() is null then
    return false;
  end if;

  select count(*) into recent_count
  from public.admin_rate_limit_buckets
  where user_id = auth.uid()
    and action = p_action
    and created_at > now() - interval '1 minute';

  if recent_count >= 30 then
    return false;
  end if;

  insert into public.admin_rate_limit_buckets (user_id, action)
  values (auth.uid(), p_action);

  return true;
end;
$$;

create or replace function public.archive_member(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;
  if not public.check_admin_rate_limit('archive_member') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.members set deleted_at = now() where id = p_id and deleted_at is null;
end;
$$;

create or replace function public.restore_member(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;
  if not public.check_admin_rate_limit('restore_member') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.members set deleted_at = null where id = p_id;
end;
$$;

create or replace function public.archive_announcement(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;
  if not public.check_admin_rate_limit('archive_announcement') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.announcements set deleted_at = now() where id = p_id and deleted_at is null;
end;
$$;

create or replace function public.restore_announcement(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;
  if not public.check_admin_rate_limit('restore_announcement') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.announcements set deleted_at = null where id = p_id;
end;
$$;

create or replace function public.archive_schedule_item(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;
  if not public.check_admin_rate_limit('archive_schedule_item') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.schedule_items set deleted_at = now() where id = p_id and deleted_at is null;
end;
$$;

create or replace function public.restore_schedule_item(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;
  if not public.check_admin_rate_limit('restore_schedule_item') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.schedule_items set deleted_at = null where id = p_id;
end;
$$;

create or replace function public.archive_prayer_request(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;
  if not public.check_admin_rate_limit('archive_prayer_request') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.prayer_requests set deleted_at = now() where id = p_id and deleted_at is null;
end;
$$;

create or replace function public.restore_prayer_request(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;
  if not public.check_admin_rate_limit('restore_prayer_request') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.prayer_requests set deleted_at = null where id = p_id;
end;
$$;

create or replace function public.archive_ministry(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;
  if not public.check_admin_rate_limit('archive_ministry') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.ministries set deleted_at = now() where id = p_id and deleted_at is null;
end;
$$;

create or replace function public.restore_ministry(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;
  if not public.check_admin_rate_limit('restore_ministry') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.ministries set deleted_at = null where id = p_id;
end;
$$;

create or replace function public.find_member_duplicates(
  p_full_name text,
  p_cpf text,
  p_email text,
  p_phone text
)
returns table (
  member_id uuid,
  full_name text,
  score numeric,
  match_reason text
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  phone_digits text := regexp_replace(coalesce(p_phone, ''), '\D+', '', 'g');
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;

  return query
  with candidates as (
    select
      m.id as member_id,
      m.full_name as full_name,
      case
        when p_cpf is not null and p_cpf <> '' and m.cpf = p_cpf then 1.0
        when p_email <> '' and lower(m.email) = lower(p_email) then 0.9
        when phone_digits <> '' and regexp_replace(coalesce(m.phone, ''), '\D+', '', 'g') = phone_digits then 0.85
        when phone_digits <> '' and regexp_replace(coalesce(m.whatsapp, ''), '\D+', '', 'g') = phone_digits then 0.85
        when similarity(m.full_name, coalesce(p_full_name, '')) > 0.7 then similarity(m.full_name, p_full_name)::numeric
        else 0
      end as score,
      case
        when p_cpf is not null and p_cpf <> '' and m.cpf = p_cpf then 'cpf_match'
        when p_email <> '' and lower(m.email) = lower(p_email) then 'email_match'
        when phone_digits <> '' and regexp_replace(coalesce(m.phone, ''), '\D+', '', 'g') = phone_digits then 'phone_match'
        when phone_digits <> '' and regexp_replace(coalesce(m.whatsapp, ''), '\D+', '', 'g') = phone_digits then 'phone_match'
        when similarity(m.full_name, coalesce(p_full_name, '')) > 0.7 then 'name_similar'
        else null
      end as match_reason
    from public.members m
    where m.deleted_at is null
  )
  select c.member_id, c.full_name, c.score, c.match_reason
  from candidates c
  where c.score > 0
  order by c.score desc
  limit 5;
end;
$$;

create or replace function public.purge_old_prayers()
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  affected int;
begin
  with purged as (
    update public.prayer_requests
    set deleted_at = now()
    where status = 'concluido'
      and updated_at < now() - interval '18 months'
      and deleted_at is null
    returning 1
  )
  select count(*) into affected from purged;
  return affected;
end;
$$;

create or replace function public.anonymize_member(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;
  if not public.check_admin_rate_limit('anonymize_member') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;

  update public.members
  set
    full_name = '[anonimizado]',
    preferred_name = '',
    birth_date = null,
    marital_status = null,
    gender = null,
    photo_url = '',
    email = '',
    phone = '',
    whatsapp = '',
    cpf = null,
    rg = '',
    rg_issuer = '',
    profession = '',
    address_zip = '',
    address_street = '',
    address_number = '',
    address_complement = '',
    address_neighborhood = '',
    address_city = '',
    address_state = '',
    baptism_location = '',
    transferred_from = '',
    emergency_contact_name = '',
    emergency_contact_phone = '',
    prayer_topics = '{}',
    spiritual_gifts = '{}',
    allergies = '',
    medical_notes = '',
    consent_medical_data_at = null,
    volunteer_notes = '',
    notes = '[anonimizado]',
    consent_given_at = null,
    consent_version = '',
    public_directory = false,
    deleted_at = coalesce(deleted_at, now())
  where id = p_id;
end;
$$;


-- =============================================================================
-- 6. Indexes
-- =============================================================================

create index schedule_starts_at_idx on public.schedule_items (starts_at);
create index schedule_scheduled_starts_at_idx
  on public.schedule_items (starts_at)
  where status = 'scheduled';
create index schedule_ministry_idx on public.schedule_items (ministry);
create index schedule_series_id_idx on public.schedule_items (series_id);

create index announcements_pinned_published_at_idx
  on public.announcements (published_at desc)
  where pinned = true;
create index announcements_status_published_at_idx
  on public.announcements (status, published_at desc);

create index prayer_requests_created_at_idx
  on public.prayer_requests (created_at desc);
create index prayer_requests_assigned_to_idx
  on public.prayer_requests (assigned_to)
  where assigned_to is not null;
create index prayer_requests_active_idx
  on public.prayer_requests (created_at desc)
  where deleted_at is null;
create index prayer_rate_limits_ip_created_at_idx
  on public.prayer_request_rate_limits (ip_hash, created_at desc);

create index ministries_sort_order_idx on public.ministries (sort_order);
create index ministries_active_idx on public.ministries (sort_order) where deleted_at is null;

create index announcements_active_idx
  on public.announcements (published_at desc)
  where deleted_at is null;

create index schedule_items_active_idx
  on public.schedule_items (starts_at)
  where deleted_at is null;

create unique index members_cpf_unique
  on public.members (cpf)
  where cpf is not null and deleted_at is null;
create index members_email_idx on public.members (email);
create index members_phone_idx on public.members (phone);
create index members_household_id_idx on public.members (household_id);
create index members_is_volunteer_idx on public.members (is_volunteer) where is_volunteer = true;
create index members_deleted_at_idx on public.members (deleted_at);
create index members_full_name_trgm_idx on public.members using gin (full_name gin_trgm_ops);

create index households_deleted_at_idx on public.households (deleted_at);

create index member_relationships_from_idx on public.member_relationships (from_member_id);
create index member_relationships_to_idx on public.member_relationships (to_member_id);

create index admin_rate_limit_buckets_user_created_idx
  on public.admin_rate_limit_buckets (user_id, created_at desc);

create index recurring_meetings_sort_order_idx
  on public.recurring_meetings (sort_order);
create index recurring_meetings_weekday_idx
  on public.recurring_meetings (weekday);

create index content_audit_log_changed_at_idx
  on public.content_audit_log (changed_at desc);
create index content_audit_log_table_row_idx
  on public.content_audit_log (table_name, row_id, changed_at desc);


-- =============================================================================
-- 7. Triggers
-- =============================================================================

-- 7.1 updated_at touch ------------------------------------------------------
create trigger touch_announcements_updated_at
before update on public.announcements
for each row execute function public.touch_updated_at();

create trigger touch_schedule_items_updated_at
before update on public.schedule_items
for each row execute function public.touch_updated_at();

create trigger touch_prayer_requests_updated_at
before update on public.prayer_requests
for each row execute function public.touch_updated_at();

create trigger touch_members_updated_at
before update on public.members
for each row execute function public.touch_updated_at();

create trigger touch_households_updated_at
before update on public.households
for each row execute function public.touch_updated_at();

create trigger touch_church_profile_updated_at
before update on public.church_profile
for each row execute function public.touch_updated_at();

create trigger touch_ministries_updated_at
before update on public.ministries
for each row execute function public.touch_updated_at();

create trigger touch_recurring_meetings_updated_at
before update on public.recurring_meetings
for each row execute function public.touch_updated_at();

-- 7.2 Audit log -------------------------------------------------------------
create trigger audit_announcements
after insert or update or delete on public.announcements
for each row execute function public.log_content_audit();

create trigger audit_schedule_items
after insert or update or delete on public.schedule_items
for each row execute function public.log_content_audit();

create trigger audit_prayer_requests
after insert or update or delete on public.prayer_requests
for each row execute function public.log_content_audit();

create trigger audit_members
after insert or update or delete on public.members
for each row execute function public.log_content_audit();

create trigger audit_households
after insert or update or delete on public.households
for each row execute function public.log_content_audit();

create trigger audit_member_relationships
after insert or update or delete on public.member_relationships
for each row execute function public.log_content_audit();

create trigger audit_church_profile
after insert or update or delete on public.church_profile
for each row execute function public.log_content_audit();

create trigger audit_ministries
after insert or update or delete on public.ministries
for each row execute function public.log_content_audit();

create trigger audit_recurring_meetings
after insert or update or delete on public.recurring_meetings
for each row execute function public.log_content_audit();


-- =============================================================================
-- 8. Row Level Security and policies
-- =============================================================================

alter table public.admin_users enable row level security;
alter table public.announcements enable row level security;
alter table public.schedule_items enable row level security;
alter table public.members enable row level security;
alter table public.households enable row level security;
alter table public.member_relationships enable row level security;
alter table public.prayer_requests enable row level security;
alter table public.prayer_request_rate_limits enable row level security;
alter table public.content_audit_log enable row level security;
alter table public.church_profile enable row level security;
alter table public.ministries enable row level security;
alter table public.recurring_meetings enable row level security;
alter table public.admin_rate_limit_buckets enable row level security;

create policy "admins can read own admin row"
  on public.admin_users for select
  to authenticated
  using (user_id = auth.uid());

create policy "owners can manage admin users"
  on public.admin_users for all
  to authenticated
  using (public.is_owner())
  with check (public.is_owner());

create policy "public can read announcements"
  on public.announcements for select
  to anon, authenticated
  using (deleted_at is null);

create policy "admins can read all announcements"
  on public.announcements for select
  to authenticated
  using (public.is_admin());

create policy "admins can insert announcements"
  on public.announcements for insert
  to authenticated
  with check (public.is_admin());

create policy "admins can update announcements"
  on public.announcements for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "public can read schedule"
  on public.schedule_items for select
  to anon, authenticated
  using (deleted_at is null);

create policy "admins can read all schedule"
  on public.schedule_items for select
  to authenticated
  using (public.is_admin());

create policy "admins can insert schedule"
  on public.schedule_items for insert
  to authenticated
  with check (public.is_admin());

create policy "admins can update schedule"
  on public.schedule_items for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "public can read public members"
  on public.members for select
  to anon, authenticated
  using (deleted_at is null and public_directory = true);

create policy "admins can read all members"
  on public.members for select
  to authenticated
  using (public.is_admin());

create policy "admins can insert members"
  on public.members for insert
  to authenticated
  with check (public.is_admin());

create policy "admins can update members"
  on public.members for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "admins can read households"
  on public.households for select
  to authenticated
  using (public.is_admin());

create policy "admins can insert households"
  on public.households for insert
  to authenticated
  with check (public.is_admin());

create policy "admins can update households"
  on public.households for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "admins can read member relationships"
  on public.member_relationships for select
  to authenticated
  using (public.is_admin());

create policy "admins can insert member relationships"
  on public.member_relationships for insert
  to authenticated
  with check (public.is_admin());

create policy "admins can update member relationships"
  on public.member_relationships for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "admins can delete member relationships"
  on public.member_relationships for delete
  to authenticated
  using (public.is_admin());

create policy "admins can read prayer requests"
  on public.prayer_requests for select
  to authenticated
  using (public.is_admin());

create policy "admins can insert prayer requests"
  on public.prayer_requests for insert
  to authenticated
  with check (public.is_admin());

create policy "admins can update prayer requests"
  on public.prayer_requests for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "admins can read audit log"
  on public.content_audit_log for select
  to authenticated
  using (public.is_admin());

create policy "public can read church profile"
  on public.church_profile for select
  to anon, authenticated
  using (true);

create policy "admins can write church profile"
  on public.church_profile for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "public can read ministries"
  on public.ministries for select
  to anon, authenticated
  using (deleted_at is null);

create policy "admins can read all ministries"
  on public.ministries for select
  to authenticated
  using (public.is_admin());

create policy "admins can insert ministries"
  on public.ministries for insert
  to authenticated
  with check (public.is_admin());

create policy "admins can update ministries"
  on public.ministries for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "public can read recurring meetings"
  on public.recurring_meetings for select
  to anon, authenticated
  using (true);

create policy "admins can write recurring meetings"
  on public.recurring_meetings for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());


-- The admin_rate_limit_buckets table is only writable through SECURITY DEFINER
-- RPCs (check_admin_rate_limit). No direct client access at all.

-- Legacy compat view: codigo antigo lia volunteers como tabela. Agora membros
-- com is_volunteer=true sao a fonte; a view derivacomo se fosse volunteers.
create view public.volunteers as
select
  m.id,
  m.full_name as name,
  case
    when array_length(m.volunteer_ministries, 1) > 0 then m.volunteer_ministries[1]
    else 'geral'
  end as role,
  0 as sort_order,
  coalesce(nullif(m.whatsapp, ''), nullif(m.phone, ''), m.email) as contact,
  m.photo_url,
  m.volunteer_ministries as ministries,
  m.volunteer_unavailable_dates as unavailable_dates,
  m.volunteer_notes as notes,
  m.created_at,
  m.updated_at
from public.members m
where m.is_volunteer = true and m.deleted_at is null;


-- =============================================================================
-- 9. Schedule seed (auto-generated from supabase/sources/*.xlsx)
-- =============================================================================
-- Run `npm run seed:schedule` to regenerate everything between the SEED markers
-- below. Do not edit by hand: changes will be overwritten.

-- BEGIN SEED ------------------------------------------------------------------
with schedule_seed (
  id, title, ministry, starts_at, ends_at, location, summary,
  preacher, director, sound_team, passage, occasion_label, status
) as (
  values
    ('239b1c9d-b2e5-4c3c-b209-3e359641299f'::uuid, 'Culto Solene', 'culto', '2026-01-04T20:00:00.000Z'::timestamptz, '2026-01-04T22:00:00.000Z'::timestamptz, 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Aparecido Regino', '', 'Marcos 1', '', 'scheduled'::public.schedule_status),
    ('a44ccaf0-32ae-4da0-8b91-841a635b8d19'::uuid, 'Culto de Oracao', 'culto', '2026-01-06T22:30:00.000Z', '2026-01-07T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('6a33c349-acae-4cab-8534-5031f04f016d'::uuid, 'Culto de oracao', 'culto', '2026-01-08T22:30:00.000Z', '2026-01-09T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('6b85c432-d864-4245-92c5-1f20f78d4ccf'::uuid, 'Culto Solene', 'culto', '2026-01-11T20:00:00.000Z', '2026-01-11T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Ir. Gilmar Fonseca', '', 'Marcos 2', '', 'scheduled'),
    ('f26ac64f-ca88-4200-9a5e-406623e39436'::uuid, 'Culto de oracao', 'culto', '2026-01-13T22:30:00.000Z', '2026-01-14T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('236ba9b2-a104-488b-a344-8ab4b282f966'::uuid, 'Culto de oracao', 'culto', '2026-01-15T22:30:00.000Z', '2026-01-16T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('361e85a5-47a3-4b53-9631-16d916f7f682'::uuid, 'Culto Solene', 'culto', '2026-01-18T20:00:00.000Z', '2026-01-18T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Graca Lira', '', 'Marcos 3', '', 'scheduled'),
    ('9a4a6952-2d19-41cd-8723-d8664626861e'::uuid, 'Culto de oracao', 'culto', '2026-01-20T22:30:00.000Z', '2026-01-21T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('280a5eaf-5857-4391-848f-6a2a57e7669b'::uuid, 'Culto de oracao', 'culto', '2026-01-22T22:30:00.000Z', '2026-01-23T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('80dd4e40-5511-4ec7-8a6b-9f2e4cfcc6eb'::uuid, 'Culto Solene', 'culto', '2026-01-25T20:00:00.000Z', '2026-01-25T22:00:00.000Z', 'Templo principal', '', 'Sem. Ruth Alves', 'Diac. Juliana Goberto', '', 'Marcos 4', '', 'scheduled'),
    ('027d678a-7ef9-443b-ab9e-d7d010f8c791'::uuid, 'Escola Biblica', 'escola-biblica', '2026-01-25T12:30:00.000Z', '2026-01-25T14:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', '', '', '', '', 'scheduled'),
    ('9837328f-32c9-4b0f-aea3-6e1f4393f03f'::uuid, 'Culto de oracao', 'culto', '2026-01-27T22:30:00.000Z', '2026-01-28T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('f63ed99f-8941-4166-9a92-a87117080de4'::uuid, 'Culto de Doutrina', 'culto', '2026-01-29T22:30:00.000Z', '2026-01-30T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('1f5f5795-c34e-494e-89f4-f5efa05056e9'::uuid, 'Culto Solene', 'culto', '2026-02-01T20:00:00.000Z', '2026-02-01T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Salete de Kassia', '', 'Marcos 5', '', 'scheduled'),
    ('4577f66d-5b83-461c-8538-752800fc2174'::uuid, 'Escola Biblica', 'escola-biblica', '2026-02-01T12:30:00.000Z', '2026-02-01T14:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', '', '', '', '', 'scheduled'),
    ('00dcb2ef-faea-48ca-8c39-a8f822ed37e2'::uuid, 'Culto de Oracao', 'culto', '2026-02-03T22:30:00.000Z', '2026-02-03T23:30:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('ed71f882-4a20-4486-9e58-84eb11b258f1'::uuid, 'Culto de Doutrina', 'culto', '2026-02-05T22:30:00.000Z', '2026-02-06T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('cd18700f-9212-4208-a3b3-098dd41ed6a2'::uuid, 'Culto Solene', 'culto', '2026-02-08T20:00:00.000Z', '2026-02-08T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Ir. Lisiane Flavia Lopes', '', 'Marcos 6', '', 'scheduled'),
    ('ea1c6b23-25bc-4ddc-9193-66a7b4f33977'::uuid, 'Escola Biblica', 'escola-biblica', '2026-02-08T12:30:00.000Z', '2026-02-08T14:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', '', '', '', '', 'scheduled'),
    ('410b4d3c-0066-4c41-9af1-2ea841885673'::uuid, 'Culto na praca', 'culto', '2026-02-10T22:30:00.000Z', '2026-02-11T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('25b4f0f1-081d-4eb9-b217-21e62bbd9469'::uuid, 'Culto de Doutrina', 'culto', '2026-02-12T22:30:00.000Z', '2026-02-13T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('e028aae8-3525-41f4-9f9e-3709ede0587f'::uuid, 'Culto Solene', 'culto', '2026-02-15T20:00:00.000Z', '2026-02-15T22:00:00.000Z', 'Templo principal', '', 'Sem. Gediael Kallebe', 'Diac. Simone Oliveira', '', 'Marcos 7', 'CARNAVAL', 'scheduled'),
    ('426b29fe-b957-4784-b859-1a4d78b3fc49'::uuid, 'Escola Biblica', 'escola-biblica', '2026-02-15T12:30:00.000Z', '2026-02-15T14:00:00.000Z', 'Templo principal', '', '', '', '', '', 'CARNAVAL', 'suspended'),
    ('1a76af01-596f-4b64-be6d-16db294f3f68'::uuid, 'Culto de Oracao', 'culto', '2026-02-17T22:30:00.000Z', '2026-02-18T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'suspended'),
    ('bb7fb112-8f2d-4086-a8ad-9845152cad1a'::uuid, 'Culto de Doutrina', 'culto', '2026-02-19T22:30:00.000Z', '2026-02-20T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('02bd4930-5e4f-410c-9507-3380cd1c3002'::uuid, 'Culto Solene', 'culto', '2026-02-22T20:00:00.000Z', '2026-02-22T22:00:00.000Z', 'Templo principal', '', 'Sem. Ruth Alves', 'Diac. Adeildo Natalicio', '', '', '', 'scheduled'),
    ('9a215288-2f23-435a-942e-ca991458cee1'::uuid, 'Escola Biblica', 'escola-biblica', '2026-02-22T12:30:00.000Z', '2026-02-22T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('7875f4a3-be36-4122-af6c-450756b32039'::uuid, 'Culto na praca', 'culto', '2026-02-24T22:30:00.000Z', '2026-02-25T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('37b4290f-7cd9-4ae8-8767-20df23b38ae8'::uuid, 'Culto de Doutrina', 'culto', '2026-02-26T22:30:00.000Z', '2026-02-27T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('a6aab69a-fbd6-47d6-b36c-fdbc770a0ff2'::uuid, 'Culto Solene', 'culto', '2026-03-01T20:00:00.000Z', '2026-03-01T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Ir. Ana Amelia', 'Ir. Miguel', 'Marcos 9', '', 'scheduled'),
    ('48bcf1ee-b5fd-489a-bc65-c266950aed50'::uuid, 'Escola Biblica', 'escola-biblica', '2026-03-01T12:30:00.000Z', '2026-03-01T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('fd45dd51-1a5b-4115-a6fc-7834b4dabe78'::uuid, 'Culto de Oracao', 'culto', '2026-03-03T22:30:00.000Z', '2026-03-04T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('81ffe2cc-a300-48de-ae29-b7bd70d44fa5'::uuid, 'Culto de Doutrina', 'culto', '2026-03-05T22:30:00.000Z', '2026-03-06T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('eda4bd10-2ead-47cc-a65b-666999b78752'::uuid, 'Culto Solene', 'culto', '2026-03-08T20:00:00.000Z', '2026-03-08T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Ir. Ana Dupont', 'Ir. Brainer', 'Marcos 10', 'Dia Internacional da Mulher', 'scheduled'),
    ('eb9a288b-d0b7-4720-8c6e-cca5372ffdd1'::uuid, 'Escola Biblica', 'escola-biblica', '2026-03-08T12:30:00.000Z', '2026-03-08T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('ae945e17-6382-4636-91ef-f150b4251a01'::uuid, 'Culto na praca', 'culto', '2026-03-10T22:30:00.000Z', '2026-03-11T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('2f573ee3-8d07-47f4-b54a-d98ea46018d3'::uuid, 'Culto de Doutrina', 'culto', '2026-03-12T22:30:00.000Z', '2026-03-13T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('be794162-199e-4c68-99e5-d4552ddcd72d'::uuid, 'Culto Solene', 'culto', '2026-03-15T20:00:00.000Z', '2026-03-15T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Aparecido Regino', 'Ir. Fernando', 'Marcos 11', '', 'scheduled'),
    ('34fd83b7-6efb-4839-9d2f-8b814f0256a3'::uuid, 'Escola Biblica', 'escola-biblica', '2026-03-15T12:30:00.000Z', '2026-03-15T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('66aa2147-75b9-49d5-9bd8-735edd276007'::uuid, 'Culto de Oracao', 'culto', '2026-03-17T22:30:00.000Z', '2026-03-18T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('6397c481-0cea-4b90-8166-8aa90249f93a'::uuid, 'Culto de Doutrina', 'culto', '2026-03-19T22:30:00.000Z', '2026-03-20T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('33ecc6e8-be0a-498f-8574-718c247425a7'::uuid, 'Culto Solene', 'culto', '2026-03-22T20:00:00.000Z', '2026-03-22T22:00:00.000Z', 'Templo principal', '', 'Sem. Gediael Kallebe', 'Ir. Gilmar Fonseca', 'Ir. Leandro', 'Marcos 12', '', 'scheduled'),
    ('c57de839-9d40-429f-815a-d5ce15b57053'::uuid, 'Escola Biblica', 'escola-biblica', '2026-03-22T12:30:00.000Z', '2026-03-22T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('238a1b6b-b9b8-4cb4-b812-61346e04259c'::uuid, 'Culto na praca', 'culto', '2026-03-24T22:30:00.000Z', '2026-03-25T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('66c86b04-1b97-407a-94ec-5b41b1125204'::uuid, 'Culto de Doutrina', 'culto', '2026-03-26T22:30:00.000Z', '2026-03-27T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('0e95b345-aeb6-42b7-94d2-a526941d520f'::uuid, 'Culto Solene', 'culto', '2026-03-29T20:00:00.000Z', '2026-03-29T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Diac. Graca Lira', 'Ir. Ana Claudia', 'Marcos 13', '', 'scheduled'),
    ('df2b9c7a-b49b-4e2f-b323-f446148dd108'::uuid, 'Escola Biblica', 'escola-biblica', '2026-03-29T12:30:00.000Z', '2026-03-29T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('a2a29fd7-4b40-421d-ab46-cc220d6cbf5f'::uuid, 'Culto de Oracao', 'culto', '2026-03-31T22:30:00.000Z', '2026-04-01T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('f124603e-32af-40cc-8beb-81f7144b5485'::uuid, 'Culto de Louvor', 'culto', '2026-04-02T22:30:00.000Z', '2026-04-03T00:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', '', '', '', '', 'scheduled'),
    ('4c60c669-a0f3-484d-8970-bfcb1ecec0c9'::uuid, 'Culto Solene', 'culto', '2026-04-05T20:00:00.000Z', '2026-04-05T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Juliana Goberto', 'Ir. Miguel', 'Marcos 14', 'PASCOA', 'scheduled'),
    ('edbc4e56-6058-4205-865f-bb6e512a0266'::uuid, 'Escola Biblica', 'escola-biblica', '2026-04-05T12:30:00.000Z', '2026-04-05T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('1f361e15-811d-4ead-8203-bd47e50e3aa2'::uuid, 'Culto na praca', 'culto', '2026-04-07T22:30:00.000Z', '2026-04-08T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('506c9005-883b-4c92-b287-a121c2c1f3a5'::uuid, 'Culto de Louvor', 'culto', '2026-04-09T22:30:00.000Z', '2026-04-10T00:00:00.000Z', 'Templo principal', '', 'Sem. Gediael Kallebe', 'Ir. Dilma Martins', '', '', '', 'scheduled'),
    ('b7d461db-3b54-4c3f-a071-7ec8df9c9923'::uuid, 'Culto Solene', 'culto', '2026-04-12T20:00:00.000Z', '2026-04-12T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Diac. Salete de Kassia', 'Ir. Brainer', 'Marcos 15', '', 'scheduled'),
    ('9a25cdbb-99b8-4aad-8c69-5fa12ca47598'::uuid, 'Escola Biblica', 'escola-biblica', '2026-04-12T12:30:00.000Z', '2026-04-12T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('5d9645ba-dbc1-49d4-bee6-a3f9e07f117c'::uuid, 'Culto de Oracao', 'culto', '2026-04-14T22:30:00.000Z', '2026-04-15T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('2f8a95a9-81bb-4a04-abb5-0f61846037ea'::uuid, 'Culto de Louvor', 'culto', '2026-04-16T22:30:00.000Z', '2026-04-17T00:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Sem. Ruth Alves', '', '', '', 'scheduled'),
    ('7536a2e1-1380-45cc-b9b9-f7ab15578d70'::uuid, 'Culto Solene', 'culto', '2026-04-19T20:00:00.000Z', '2026-04-19T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Ir. Lisiane Flavia Lopes', 'Ir. Fernando', 'Marcos 16', '', 'scheduled'),
    ('e5ec8110-324f-44d3-b9e1-d05fc3bc46b9'::uuid, 'Escola Biblica', 'escola-biblica', '2026-04-19T12:30:00.000Z', '2026-04-19T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('e5a5133e-cb7d-47f6-a79a-fc7caba01b60'::uuid, 'Culto na praca', 'culto', '2026-04-21T22:30:00.000Z', '2026-04-22T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('4ea211d1-31c5-4af6-bd71-57bfef5c0cf9'::uuid, 'Culto de Louvor', 'culto', '2026-04-23T22:30:00.000Z', '2026-04-24T00:00:00.000Z', 'Templo principal', '', 'Sem. Ruth Alves', 'Ir. Edjane', '', '', '', 'scheduled'),
    ('31a5fe1e-cee6-4c6a-9546-dfe8bee6000f'::uuid, 'Culto Solene', 'culto', '2026-04-26T20:00:00.000Z', '2026-04-26T22:00:00.000Z', 'Templo principal', '', 'Sem. Ruth Alves', 'Diac. Simone Oliveira', 'Ir. Leandro', 'Apocalipse 1', '', 'scheduled'),
    ('aceca2dc-e56b-4576-b344-9e2518e4bf03'::uuid, 'Escola Biblica', 'escola-biblica', '2026-04-26T12:30:00.000Z', '2026-04-26T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('f8eb320e-2f3d-4fcf-be49-b76c513b563e'::uuid, 'Culto de Oracao', 'culto', '2026-04-28T22:30:00.000Z', '2026-04-29T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('e023bccd-18ab-4e9c-8569-62217a5ca4eb'::uuid, 'Culto de Louvor', 'culto', '2026-04-30T22:30:00.000Z', '2026-05-01T00:00:00.000Z', 'Templo principal', '', 'Ir. Ana Claudia', 'ADOLESCENTES', '', '', '', 'scheduled'),
    ('92497d1d-98a8-44d6-a54a-847231711384'::uuid, 'Culto Solene', 'culto', '2026-05-03T20:00:00.000Z', '2026-05-03T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Adeildo Natalicio', 'Ir. Ana Claudia', 'Apocalipse 2', 'MES DE MISSOES', 'scheduled'),
    ('264f09d2-12e1-4d77-81fd-02fb64149d6d'::uuid, 'Escola Biblica', 'escola-biblica', '2026-05-03T12:30:00.000Z', '2026-05-03T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('f082db35-fb99-4d54-8165-8747fcdbf73f'::uuid, 'Encontro de Mulheres', 'mulheres', '2026-05-05T22:30:00.000Z', '2026-05-06T00:00:00.000Z', 'Templo principal', '', '', 'Sem. Ruth Alves', '', '', '', 'scheduled'),
    ('7caa8a3a-fa39-4719-8e62-9c2387b9a5c3'::uuid, 'Culto de Louvor', 'culto', '2026-05-07T22:30:00.000Z', '2026-05-08T00:00:00.000Z', 'Templo principal', '', 'Diac. Adeildo Natalicio', 'Ir. Fabiana', '', '', '', 'scheduled'),
    ('beca5818-594f-430d-abe4-bd71137becb9'::uuid, 'Culto Solene', 'culto', '2026-05-10T20:00:00.000Z', '2026-05-10T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Ir. Ana Amelia', 'Ir. Miguel', 'Apocalipse 3', 'MES DE MISSOES (Dia das maes)', 'scheduled'),
    ('0187b1d9-c7e2-408e-98d8-8e68ab198ac3'::uuid, 'Escola Biblica', 'escola-biblica', '2026-05-10T12:30:00.000Z', '2026-05-10T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('9be1c4b4-07c3-4628-9031-8c38947a4d1b'::uuid, 'Livre', 'geral', '2026-05-12T22:30:00.000Z', '2026-05-13T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('3f2c152e-0a4c-4300-85a1-49137bb3f94e'::uuid, 'Culto de Louvor', 'culto', '2026-05-14T22:30:00.000Z', '2026-05-15T00:00:00.000Z', 'Templo principal', '', 'Diac. Aparecido Regino', 'Sem. Gediael Kallebe', '', '', '', 'scheduled'),
    ('63234c54-7210-4583-a5ee-211254135b65'::uuid, 'Culto Solene', 'culto', '2026-05-17T20:00:00.000Z', '2026-05-17T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Ir. Ana Dupont', 'Ir. Brainer', 'Apocalipse 4', 'MES DE MISSOES', 'scheduled'),
    ('487174c5-78a5-427d-a3e3-85d2535f276b'::uuid, 'Escola Biblica', 'escola-biblica', '2026-05-17T12:30:00.000Z', '2026-05-17T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('2fdb22a2-c694-4a74-9eac-0aae902d2fd9'::uuid, 'Culto na praca', 'culto', '2026-05-19T22:30:00.000Z', '2026-05-20T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('3237e3f2-6a89-42e6-883e-f4b18355f08e'::uuid, 'Culto de Louvor', 'culto', '2026-05-21T22:30:00.000Z', '2026-05-22T00:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Graca Lira', '', '', '', 'scheduled'),
    ('14e093f3-218f-4863-b489-b1fc5c966fc6'::uuid, 'Culto Solene', 'culto', '2026-05-24T20:00:00.000Z', '2026-05-24T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Diac. Aparecido Regino', 'Ir. Fernando', 'Apocalipse 5', 'MES DE MISSOES', 'scheduled'),
    ('163b4fcb-0b0c-41e4-b7dc-6ff2dfee371c'::uuid, 'Escola Biblica', 'escola-biblica', '2026-05-24T12:30:00.000Z', '2026-05-24T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('c14011d2-15e1-4e14-b382-3d023bd1e9ae'::uuid, 'Livre', 'geral', '2026-05-26T22:30:00.000Z', '2026-05-27T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('e0166fab-bed5-4e7a-95b1-c72cef02a09a'::uuid, 'Culto de Louvor', 'culto', '2026-05-28T22:30:00.000Z', '2026-05-29T00:00:00.000Z', 'Templo principal', '', 'Sem. Gediael Kallebe', 'VAROES', '', '', '', 'scheduled'),
    ('b6191589-d1a1-40a0-b543-9eabe4f29874'::uuid, 'Culto Solene', 'culto', '2026-05-31T20:00:00.000Z', '2026-05-31T22:00:00.000Z', 'Templo principal', '', 'Sem. Gediael Kallebe', 'Ir. Gilmar Fonseca', 'Ir. Leandro', 'Apocalipse 6', 'MES DE MISSOES', 'scheduled'),
    ('1fa4ccdb-b592-4a25-b6a5-adf4e36a9019'::uuid, 'Escola Biblica', 'escola-biblica', '2026-05-31T12:30:00.000Z', '2026-05-31T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('3837ba15-1fe4-43c5-8129-c3a82e1bf06a'::uuid, 'Encontro de Mulheres', 'mulheres', '2026-06-02T22:30:00.000Z', '2026-06-03T00:00:00.000Z', 'Templo principal', '', '', 'Sem. Ruth Alves', '', '', '', 'scheduled'),
    ('813d9ea4-21f7-4db6-8cb1-410f25a3b990'::uuid, 'Culto de Louvor', 'culto', '2026-06-04T22:30:00.000Z', '2026-06-05T00:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Diac. Salete de Kassia', '', '', '', 'scheduled'),
    ('9f9aca1d-4cc4-49ba-9b9a-0dae4804f615'::uuid, 'Culto Solene', 'culto', '2026-06-07T20:00:00.000Z', '2026-06-07T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Graca Lira', 'Ir. Ana Claudia', 'Apocalipse 7', '', 'scheduled'),
    ('60251c32-bb13-458e-89ff-8fb70823f75d'::uuid, 'Escola Biblica', 'escola-biblica', '2026-06-07T12:30:00.000Z', '2026-06-07T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('dcc16272-546a-4600-a05b-c739b8848a7e'::uuid, 'Livre', 'geral', '2026-06-09T22:30:00.000Z', '2026-06-10T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('ae174f65-8f20-4721-889e-5b66ac19c62e'::uuid, 'Culto de Louvor', 'culto', '2026-06-11T22:30:00.000Z', '2026-06-12T00:00:00.000Z', 'Templo principal', '', 'Sem. Ruth Alves', 'Ir. Ana Amelia', '', '', '', 'scheduled'),
    ('d3c95f7a-96de-4f3f-b76e-8b7245a20430'::uuid, 'Culto Solene', 'culto', '2026-06-14T20:00:00.000Z', '2026-06-14T22:00:00.000Z', 'Templo principal', '', 'Convidado', 'Pr. Augusto Lopes', 'Ir. Miguel', 'Apocalipse 8', '', 'scheduled'),
    ('a71b5aae-becb-4884-86a0-749a1fb7c0b4'::uuid, 'Escola Biblica', 'escola-biblica', '2026-06-14T12:30:00.000Z', '2026-06-14T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('71d83d7b-e470-450a-9cd7-2acd46a5750a'::uuid, 'Culto na praca', 'culto', '2026-06-16T22:30:00.000Z', '2026-06-17T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('0119909b-4f5c-4208-b2f8-05eb9b321cd9'::uuid, 'Culto de Louvor', 'culto', '2026-06-18T22:30:00.000Z', '2026-06-19T00:00:00.000Z', 'Templo principal', '', 'Ir. Ana Claudia', 'Ir. Lisiane Flavia Lopes', '', '', '', 'scheduled'),
    ('45efdfa4-300d-4c1a-bd01-9f6df63c785c'::uuid, 'Culto Solene', 'culto', '2026-06-21T20:00:00.000Z', '2026-06-21T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Diac. Juliana Goberto', 'Ir. Brainer', 'Apocalipse 9', '', 'scheduled'),
    ('59260a70-9da7-4f70-ba03-110e69d88c99'::uuid, 'Escola Biblica', 'escola-biblica', '2026-06-21T12:30:00.000Z', '2026-06-21T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('4219531b-e8a4-46ae-9121-53d0bb6b7a31'::uuid, 'Livre', 'geral', '2026-06-23T22:30:00.000Z', '2026-06-24T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('ddf94a72-fb8c-4467-b802-8793b574eb36'::uuid, 'Culto de Louvor', 'culto', '2026-06-25T22:30:00.000Z', '2026-06-26T00:00:00.000Z', 'Templo principal', '', 'Diac. Adeildo Natalicio', 'UFBB', '', '', '', 'scheduled'),
    ('b87e7351-83b7-4ae5-ae4b-60c718f47aaf'::uuid, 'Culto Solene', 'culto', '2026-06-28T20:00:00.000Z', '2026-06-28T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Salete de Kassia', 'Ir. Fernando', 'Apocalipse 10', '', 'scheduled'),
    ('32fd15b9-106b-4770-8b42-97e0b50e45b6'::uuid, 'Escola Biblica', 'escola-biblica', '2026-06-28T12:30:00.000Z', '2026-06-28T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('5c451fa4-35cf-48b5-a878-b55a377f2f44'::uuid, 'Culto na praca', 'culto', '2026-06-30T22:30:00.000Z', '2026-07-01T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('4a1b0918-529c-421a-b10c-6f5d94ec3771'::uuid, 'Culto de Louvor', 'culto', '2026-07-02T22:30:00.000Z', '2026-07-03T00:00:00.000Z', 'Templo principal', '', 'Diac. Aparecido Regino', 'Diac. Luciano', '', '', '', 'scheduled'),
    ('c40d2103-5d60-45ea-a2f3-e051e4cb33c1'::uuid, 'Culto Solene', 'culto', '2026-07-05T20:00:00.000Z', '2026-07-05T22:00:00.000Z', 'Templo principal', '', 'Sem. Ruth Alves', 'Ir. Lisiane Flavia Lopes', 'Ir. Leandro', 'Apocalipse 11', '', 'scheduled'),
    ('8c1d4b1e-de2c-44e1-919f-6e24d4ef685f'::uuid, 'Escola Biblica', 'escola-biblica', '2026-07-05T12:30:00.000Z', '2026-07-05T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('729d72a1-b556-4edd-adf6-9ce7371da0d8'::uuid, 'Encontro de Mulheres', 'mulheres', '2026-07-07T22:30:00.000Z', '2026-07-08T00:00:00.000Z', 'Templo principal', '', '', 'Sem. Ruth Alves', '', '', '', 'scheduled'),
    ('9de02c89-8491-43b4-b741-c15b635793e3'::uuid, 'Culto de Louvor', 'culto', '2026-07-09T22:30:00.000Z', '2026-07-10T00:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Juliana Goberto', '', '', '', 'scheduled'),
    ('f9439dd8-2456-4a87-99f7-623bdd49f8c1'::uuid, 'Culto Solene', 'culto', '2026-07-12T20:00:00.000Z', '2026-07-12T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Simone Oliveira', 'Ir. Ana Claudia', 'Apocalipse 12', '', 'scheduled'),
    ('1a1b6dac-ed05-4506-a7fb-ce93898c22d8'::uuid, 'Escola Biblica', 'escola-biblica', '2026-07-12T12:30:00.000Z', '2026-07-12T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('39cc4502-0217-4070-84d9-7aa676242ec6'::uuid, 'Culto na praca', 'culto', '2026-07-14T22:30:00.000Z', '2026-07-15T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('eae0ca45-de89-4ba4-8d3e-0656c8b0c26e'::uuid, 'Culto de Louvor', 'culto', '2026-07-16T22:30:00.000Z', '2026-07-17T00:00:00.000Z', 'Templo principal', '', 'Sem. Gediael Kallebe', 'Ir. Gilmar Fonseca', '', '', '', 'scheduled'),
    ('be73a358-cc6e-414c-8999-76e5916bd9eb'::uuid, 'Culto Solene', 'culto', '2026-07-19T20:00:00.000Z', '2026-07-19T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Diac. Adeildo Natalicio', 'Ir. Miguel', 'Apocalipse 13', '', 'scheduled'),
    ('e2226a98-743c-496a-88d5-5e12ec3a8da2'::uuid, 'Escola Biblica', 'escola-biblica', '2026-07-19T12:30:00.000Z', '2026-07-19T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('83244068-def3-4853-8978-47a32a4b36f1'::uuid, 'Livre', 'geral', '2026-07-21T22:30:00.000Z', '2026-07-22T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('f3ad3aa5-ee79-4b67-807d-151ad24e97fb'::uuid, 'Culto de Louvor', 'culto', '2026-07-23T22:30:00.000Z', '2026-07-24T00:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Diac. Simone Oliveira', '', '', '', 'scheduled'),
    ('0141edf1-e16e-4131-8b33-6592b6f5e2ce'::uuid, 'Culto Solene', 'culto', '2026-07-26T20:00:00.000Z', '2026-07-26T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Ir. Ana Amelia', 'Ir. Brainer', 'Apocalipse 14', '', 'scheduled'),
    ('16197232-f4bc-46dc-a3c9-ef8667665d11'::uuid, 'Escola Biblica', 'escola-biblica', '2026-07-26T12:30:00.000Z', '2026-07-26T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('a2dc64a8-cbe2-4790-b5a8-20e2c6749145'::uuid, 'Culto na praca', 'culto', '2026-07-28T22:30:00.000Z', '2026-07-29T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('153da672-d152-4b89-9673-376840cf7b54'::uuid, 'Culto de Louvor', 'culto', '2026-07-30T22:30:00.000Z', '2026-07-31T00:00:00.000Z', 'Templo principal', '', 'Sem. Ruth Alves', 'GRUPO DE LOUVOR', '', '', '', 'scheduled'),
    ('ba79a075-1594-42ba-9895-decd12c81586'::uuid, 'Culto Solene', 'culto', '2026-08-02T20:00:00.000Z', '2026-08-02T22:00:00.000Z', 'Templo principal', '', 'Sem. Gediael Kallebe', 'Ir. Ana Dupont', 'Ir. Fernando', 'Apocalipse 15', 'MES DA FAMILIA', 'scheduled'),
    ('925155f4-c448-4fd5-be3f-a35d0a0acb4d'::uuid, 'Escola Biblica', 'escola-biblica', '2026-08-02T12:30:00.000Z', '2026-08-02T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('1e9b0206-8db7-4fc5-824e-9d4e944c4d99'::uuid, 'Encontro de Mulheres', 'mulheres', '2026-08-04T22:30:00.000Z', '2026-08-05T00:00:00.000Z', 'Templo principal', '', '', 'Sem. Ruth Alves', '', '', '', 'scheduled'),
    ('3f53c829-1b6c-4008-94cd-ce16c3c4f219'::uuid, 'Culto de Louvor', 'culto', '2026-08-06T22:30:00.000Z', '2026-08-07T00:00:00.000Z', 'Templo principal', '', 'Ir. Ana Claudia', 'Ir. Naim', '', '', '', 'scheduled'),
    ('5d2902d2-6840-4d84-bd6b-034f2721b6f8'::uuid, 'Culto Solene', 'culto', '2026-08-09T20:00:00.000Z', '2026-08-09T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Aparecido Regino', 'Ir. Leandro', 'Apocalipse 16', 'MES DA FAMILIA (dia dos pais)', 'scheduled'),
    ('397d3cae-b103-4e5e-a9a6-e80f92f02d98'::uuid, 'Escola Biblica', 'escola-biblica', '2026-08-09T12:30:00.000Z', '2026-08-09T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('55ef0971-00f1-4e03-ba9b-9798444e8fa7'::uuid, 'Culto na praca', 'culto', '2026-08-11T22:30:00.000Z', '2026-08-12T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('1360e034-686a-4966-b6c2-e1acc67535a3'::uuid, 'Culto de Louvor', 'culto', '2026-08-13T22:30:00.000Z', '2026-08-14T00:00:00.000Z', 'Templo principal', '', 'Diac. Adeildo Natalicio', 'Ir. Dilma Martins', '', '', '', 'scheduled'),
    ('633ad4f6-43fe-4430-a143-a2fdb3925b10'::uuid, 'Culto Solene', 'culto', '2026-08-16T20:00:00.000Z', '2026-08-16T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Ir. Gilmar Fonseca', 'Ir. Ana Claudia', 'Apocalipse 17', 'MES DA FAMILIA', 'scheduled'),
    ('9266f466-755e-45a1-aae1-ea8ea3781b60'::uuid, 'Escola Biblica', 'escola-biblica', '2026-08-16T12:30:00.000Z', '2026-08-16T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('d362178d-510b-49b9-839c-ea383ea5ba06'::uuid, 'Livre', 'geral', '2026-08-18T22:30:00.000Z', '2026-08-19T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('ca37caf8-6376-4e28-96fc-d2d5d2353b74'::uuid, 'Culto de Louvor', 'culto', '2026-08-20T22:30:00.000Z', '2026-08-21T00:00:00.000Z', 'Templo principal', '', 'Diac. Aparecido Regino', 'Sem. Ruth Alves', '', '', '', 'scheduled'),
    ('6b7fabc5-e08a-489c-8f07-f57aac2fa238'::uuid, 'Culto Solene', 'culto', '2026-08-23T20:00:00.000Z', '2026-08-23T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Graca Lira', 'Ir. Miguel', 'Apocalipse 18', 'MES DA FAMILIA', 'scheduled'),
    ('36cc248d-4576-455c-ad55-5ee286ac9bb5'::uuid, 'Escola Biblica', 'escola-biblica', '2026-08-23T12:30:00.000Z', '2026-08-23T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('ef2fd442-fe32-4e7f-a3fa-36ae5ae2ce8e'::uuid, 'Culto na praca', 'culto', '2026-08-25T22:30:00.000Z', '2026-08-26T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('db4d4b62-b79b-45cf-9592-3598e93cb143'::uuid, 'Culto de Louvor', 'culto', '2026-08-27T22:30:00.000Z', '2026-08-28T00:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Ir. Edjane', '', '', '', 'scheduled'),
    ('47cd0038-9172-4419-826f-2baff3803f81'::uuid, 'Culto Solene', 'culto', '2026-08-30T20:00:00.000Z', '2026-08-30T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Diac. Juliana Goberto', 'Ir. Brainer', 'Apocalipse 19', 'MES DA FAMILIA', 'scheduled'),
    ('ddca6618-4990-4ac1-9c55-f6db5d1e68a8'::uuid, 'Escola Biblica', 'escola-biblica', '2026-08-30T12:30:00.000Z', '2026-08-30T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('64ef792a-7979-4369-b11a-0c54b8adc7f6'::uuid, 'Encontro de Mulheres', 'mulheres', '2026-09-01T22:30:00.000Z', '2026-09-02T00:00:00.000Z', 'Templo principal', '', '', 'Sem. Ruth Alves', '', '', '', 'scheduled'),
    ('e8955acc-c93b-424d-b04e-60540a115b3c'::uuid, 'Culto de Louvor', 'culto', '2026-09-03T22:30:00.000Z', '2026-09-04T00:00:00.000Z', 'Templo principal', '', 'Sem. Gediael Kallebe', 'ADOLESCENTES', '', '', '', 'scheduled'),
    ('4b62a233-a13d-465e-a118-54bc12af84fa'::uuid, 'Culto Solene', 'culto', '2026-09-06T20:00:00.000Z', '2026-09-06T22:00:00.000Z', 'Templo principal', '', 'Sem. Ruth Alves', 'Diac. Salete de Kassia', 'Ir. Fernando', 'Apocalipse 20', '', 'scheduled'),
    ('e4997389-c076-45bd-88b1-7db5f10af566'::uuid, 'Escola Biblica', 'escola-biblica', '2026-09-06T12:30:00.000Z', '2026-09-06T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('3d3c8eed-db0d-4f5d-801d-f4be0a2f8a32'::uuid, 'Culto na praca', 'culto', '2026-09-08T22:30:00.000Z', '2026-09-09T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('2bc1f42c-ed65-4bfa-91d7-14bf57e83320'::uuid, 'Culto de Louvor', 'culto', '2026-09-10T22:30:00.000Z', '2026-09-11T00:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Ir. Fabiana', '', '', '', 'scheduled'),
    ('a38b6700-8462-4e5f-a77d-7fe120989d75'::uuid, 'Culto Solene', 'culto', '2026-09-13T20:00:00.000Z', '2026-09-13T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Ir. Lisiane Flavia Lopes', 'Ir. Leandro', 'Apocalipse 21', '', 'scheduled'),
    ('ba74a914-8990-4400-b917-5761047430d5'::uuid, 'Escola Biblica', 'escola-biblica', '2026-09-13T12:30:00.000Z', '2026-09-13T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('4d3cab9e-0d54-4b20-8da0-da47ccaa8d96'::uuid, 'Livre', 'geral', '2026-09-15T22:30:00.000Z', '2026-09-16T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('1a9f8dd1-bda8-4978-ad33-5be67c7bd14e'::uuid, 'Culto de Louvor', 'culto', '2026-09-17T22:30:00.000Z', '2026-09-18T00:00:00.000Z', 'Templo principal', '', 'Sem. Ruth Alves', 'Sem. Gediael Kallebe', '', '', '', 'scheduled'),
    ('e67eacd5-7b08-4ba4-8a71-165154d5865d'::uuid, 'Culto Solene', 'culto', '2026-09-20T20:00:00.000Z', '2026-09-20T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Diac. Simone Oliveira', 'Ir. Ana Claudia', 'Apocalipse 22', '', 'scheduled'),
    ('8f5866bc-8dbe-4dd6-8438-1ddab2d34d49'::uuid, 'Escola Biblica', 'escola-biblica', '2026-09-20T12:30:00.000Z', '2026-09-20T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('54566b91-0565-4a09-a5cc-bb7e5f4f3657'::uuid, 'Culto na praca', 'culto', '2026-09-22T22:30:00.000Z', '2026-09-23T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('839dff2e-4969-41d8-a30c-af66cbaf65e3'::uuid, 'Culto de Louvor', 'culto', '2026-09-24T22:30:00.000Z', '2026-09-25T00:00:00.000Z', 'Templo principal', '', 'Ir. Ana Claudia', 'Diac. Graca Lira', '', '', '', 'scheduled'),
    ('dd6843dd-b4f0-4ae8-8cf4-29090419a5c8'::uuid, 'Culto Solene', 'culto', '2026-09-27T20:00:00.000Z', '2026-09-27T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Adeildo Natalicio', 'Ir. Miguel', '2 Corintios 1', '', 'scheduled'),
    ('9d55c1d2-21f2-4d06-806a-723a110b481a'::uuid, 'Escola Biblica', 'escola-biblica', '2026-09-27T12:30:00.000Z', '2026-09-27T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('e33e9b12-e4de-4500-839b-7a384d2708ba'::uuid, 'Livre', 'geral', '2026-09-29T22:30:00.000Z', '2026-09-30T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('2a6d4652-60a3-45ea-8ff9-1339d068a657'::uuid, 'Culto de Louvor', 'culto', '2026-10-01T22:30:00.000Z', '2026-10-02T00:00:00.000Z', 'Templo principal', '', 'Diac. Adeildo Natalicio', 'VAROES', '', '', '', 'scheduled'),
    ('b05d32cf-41f1-483a-8a96-880adb684b66'::uuid, 'Culto Solene', 'culto', '2026-10-04T20:00:00.000Z', '2026-10-04T22:00:00.000Z', 'Templo principal', '', 'Sem. Gediael Kallebe', 'Ir. Ana Amelia', 'Ir. Brainer', '2 Corintios 2', 'MES DE MISSOES', 'scheduled'),
    ('e5e73354-a1d6-4e53-9ae8-02bbfc3332af'::uuid, 'Escola Biblica', 'escola-biblica', '2026-10-04T12:30:00.000Z', '2026-10-04T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('0ac6e4c6-d6ca-4394-895d-21406895c7c0'::uuid, 'Encontro de Mulheres', 'mulheres', '2026-10-06T22:30:00.000Z', '2026-10-07T00:00:00.000Z', 'Templo principal', '', '', 'Sem. Ruth Alves', '', '', '', 'scheduled'),
    ('d820c96e-02f3-4eda-a5d2-09c227eb413f'::uuid, 'Culto de Louvor', 'culto', '2026-10-08T22:30:00.000Z', '2026-10-09T00:00:00.000Z', 'Templo principal', '', 'Diac. Aparecido Regino', 'Diac. Salete de Kassia', '', '', '', 'scheduled'),
    ('08bba675-4fd7-4bd2-9f32-30ef7d547791'::uuid, 'Culto Solene', 'culto', '2026-10-11T20:00:00.000Z', '2026-10-11T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Ir. Ana Dupont', 'Ir. Fernando', '2 Corintios 3', 'MES DE MISSOES', 'scheduled'),
    ('e239d351-b61c-4eea-b8ac-fbdd7ff871fb'::uuid, 'Escola Biblica', 'escola-biblica', '2026-10-11T12:30:00.000Z', '2026-10-11T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('bbe3b1a8-bc40-47ef-ba06-08cdd04f0e59'::uuid, 'Livre', 'geral', '2026-10-13T22:30:00.000Z', '2026-10-14T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('9d262275-6f06-46bb-bf43-d956efae6540'::uuid, 'Culto de Louvor', 'culto', '2026-10-15T22:30:00.000Z', '2026-10-16T00:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Ir. Ana Amelia', '', '', '', 'scheduled'),
    ('aa8ac6b4-2a01-4b26-a635-20fa488c0158'::uuid, 'Culto Solene', 'culto', '2026-10-18T20:00:00.000Z', '2026-10-18T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Diac. Aparecido Regino', 'Ir. Leandro', '2 Corintios 4', 'MES DE MISSOES', 'scheduled'),
    ('18a7a52d-6a67-43c5-bbc4-71799a761d68'::uuid, 'Escola Biblica', 'escola-biblica', '2026-10-18T12:30:00.000Z', '2026-10-18T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('f0c3f119-e11a-4659-bb57-ef386eb3f7de'::uuid, 'Culto na praca', 'culto', '2026-10-20T22:30:00.000Z', '2026-10-21T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('e66bb3e7-0d32-4049-b16e-9ce2e1889564'::uuid, 'Culto de Louvor', 'culto', '2026-10-22T22:30:00.000Z', '2026-10-23T00:00:00.000Z', 'Templo principal', '', 'Sem. Gediael Kallebe', 'Ir. Lisiane Flavia Lopes', '', '', '', 'scheduled'),
    ('bb8d663d-0ae3-4757-8600-aa286ecc5724'::uuid, 'Culto Solene', 'culto', '2026-10-25T20:00:00.000Z', '2026-10-25T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Ir. Gilmar Fonseca', 'Ir. Ana Claudia', '2 Corintios 5', 'MES DE MISSOES', 'scheduled'),
    ('60099841-b071-4abd-aae9-c97daaeeff35'::uuid, 'Escola Biblica', 'escola-biblica', '2026-10-25T12:30:00.000Z', '2026-10-25T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('87a3bece-2e0a-439b-9926-d9fe2c741220'::uuid, 'Livre', 'geral', '2026-10-27T22:30:00.000Z', '2026-10-28T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('ea5ca6c7-4cac-449a-a006-0030d9822928'::uuid, 'Culto de Louvor', 'culto', '2026-10-29T22:30:00.000Z', '2026-10-30T00:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'UFBB', '', '', '', 'scheduled'),
    ('cd625582-047b-4f3e-97ea-96817445d2d5'::uuid, 'Culto Solene', 'culto', '2026-11-01T20:00:00.000Z', '2026-11-01T22:00:00.000Z', 'Templo principal', '', 'Sem. Ruth Alves', 'Diac. Graca Lira', 'Ir. Miguel', '2 Corintios 6', '', 'scheduled'),
    ('04df6d3b-0670-419b-a73f-60bcae512b60'::uuid, 'Escola Biblica', 'escola-biblica', '2026-11-01T12:30:00.000Z', '2026-11-01T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('1543934a-8fa8-46e8-b237-7250970e4ca7'::uuid, 'Culto na praca', 'culto', '2026-11-03T22:30:00.000Z', '2026-11-04T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('253dca21-68a1-408d-878e-f92494bc1c16'::uuid, 'Culto de Louvor', 'culto', '2026-11-05T22:30:00.000Z', '2026-11-06T00:00:00.000Z', 'Templo principal', '', 'Sem. Ruth Alves', 'Diac. Luciano', '', '', '', 'scheduled'),
    ('50491a3f-9d53-40af-b43a-367482975714'::uuid, 'Culto Solene', 'culto', '2026-11-08T20:00:00.000Z', '2026-11-08T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Diac. Juliana Goberto', 'Ir. Brainer', '2 Corintios 7', '', 'scheduled'),
    ('1e88d41a-b677-4c11-bef3-a19580b78434'::uuid, 'Escola Biblica', 'escola-biblica', '2026-11-08T12:30:00.000Z', '2026-11-08T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('6d925cf1-44a2-4427-86be-460fc66c1ccf'::uuid, 'Livre', 'geral', '2026-11-10T22:30:00.000Z', '2026-11-11T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('5551557d-51ca-4b2a-be88-825d3ae8df43'::uuid, 'Culto de Louvor', 'culto', '2026-11-12T22:30:00.000Z', '2026-11-13T00:00:00.000Z', 'Templo principal', '', 'Ir. Ana Claudia', 'Diac. Juliana Goberto', '', '', '', 'scheduled'),
    ('6da800d5-5e2a-4876-8e9a-358584382436'::uuid, 'Culto Solene', 'culto', '2026-11-15T20:00:00.000Z', '2026-11-15T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Diac. Salete de Kassia', 'Ir. Fernando', '2 Corintios 8', '', 'scheduled'),
    ('eecb9c18-449e-4b01-aab9-ce17842b8283'::uuid, 'Escola Biblica', 'escola-biblica', '2026-11-15T12:30:00.000Z', '2026-11-15T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('d95317f4-0499-4476-afd2-50b33148b489'::uuid, 'Culto na praca', 'culto', '2026-11-17T22:30:00.000Z', '2026-11-18T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('26e450e6-b634-4658-846a-9a31e0a91950'::uuid, 'Culto de Louvor', 'culto', '2026-11-19T22:30:00.000Z', '2026-11-20T00:00:00.000Z', 'Templo principal', '', 'Diac. Adeildo Natalicio', 'Ir. Gilmar Fonseca', '', '', '', 'scheduled'),
    ('a5b6a3c8-1c33-4a18-9378-7736fbdf757c'::uuid, 'Culto Solene', 'culto', '2026-11-22T20:00:00.000Z', '2026-11-22T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Ir. Lisiane Flavia Lopes', 'Ir. Leandro', '2 Corintios 9', '', 'scheduled'),
    ('b7831689-e953-4c6e-8dbe-b08171fe275b'::uuid, 'Escola Biblica', 'escola-biblica', '2026-11-22T12:30:00.000Z', '2026-11-22T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('29de5db0-dccb-4aba-b2b0-047483f7d56e'::uuid, 'Livre', 'geral', '2026-11-24T22:30:00.000Z', '2026-11-25T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('b7e8cb5f-102a-426c-bfb9-a74fd60d0444'::uuid, 'Culto de Louvor', 'culto', '2026-11-26T22:30:00.000Z', '2026-11-27T00:00:00.000Z', 'Templo principal', '', 'Diac. Aparecido Regino', 'Diac. Simone Oliveira', '', '', '', 'scheduled'),
    ('001501ff-4538-4ad5-8e6a-6f26e493fc51'::uuid, 'Culto Solene', 'culto', '2026-11-29T20:00:00.000Z', '2026-11-29T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Diac. Simone Oliveira', 'Ir. Ana Claudia', '2 Corintios 10', '', 'scheduled'),
    ('00951813-07d7-45f4-86ef-9f3375b0c795'::uuid, 'Escola Biblica', 'escola-biblica', '2026-11-29T12:30:00.000Z', '2026-11-29T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('eaa3e006-6dff-45f3-b929-bc3bc0109123'::uuid, 'Culto na praca', 'culto', '2026-12-01T22:30:00.000Z', '2026-12-02T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('cf4b3cf2-8c4c-42d5-9965-e17781ddd434'::uuid, 'Culto de Louvor', 'culto', '2026-12-03T22:30:00.000Z', '2026-12-04T00:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'GRUPO DE LOUVOR', '', '', '', 'scheduled'),
    ('596548c2-4b4a-4dba-b2f4-a362ce51d324'::uuid, 'Culto Solene', 'culto', '2026-12-06T20:00:00.000Z', '2026-12-06T22:00:00.000Z', 'Templo principal', '', 'Sem. Gediael Kallebe', 'Diac. Adeildo Natalicio', 'Ir. Miguel', '2 Corintios 11', '', 'scheduled'),
    ('88c8d3de-1aa4-48d0-9ff0-553796ba388d'::uuid, 'Escola Biblica', 'escola-biblica', '2026-12-06T12:30:00.000Z', '2026-12-06T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('42309c90-42d7-421f-83c0-d2acf153c3fb'::uuid, 'Livre', 'geral', '2026-12-08T22:30:00.000Z', '2026-12-09T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('6e655652-9efd-4559-abbb-953ca31c4d77'::uuid, 'Culto de Louvor', 'culto', '2026-12-10T22:30:00.000Z', '2026-12-11T00:00:00.000Z', 'Templo principal', '', 'Sem. Gediael Kallebe', 'Ir. Naim', '', '', '', 'scheduled'),
    ('7e90b3f0-3ba2-42f4-bcdc-18333befaf2e'::uuid, 'Culto Solene', 'culto', '2026-12-13T20:00:00.000Z', '2026-12-13T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Ir. Ana Amelia', 'Ir. Brainer', '2 Corintios 12', '', 'scheduled'),
    ('ea9e442a-2193-45f0-9784-770717411140'::uuid, 'Escola Biblica', 'escola-biblica', '2026-12-13T12:30:00.000Z', '2026-12-13T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('9abe1806-66d7-4ca5-9907-74f1e3b85d68'::uuid, 'Culto na praca', 'culto', '2026-12-15T22:30:00.000Z', '2026-12-16T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('3ba9e739-52d8-46a5-9a63-6fee8b730598'::uuid, 'Culto de Louvor', 'culto', '2026-12-17T22:30:00.000Z', '2026-12-18T00:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Ir. Dilma Martins', '', '', '', 'scheduled'),
    ('453de98c-57c8-44da-8a44-ebaa3afd1e92'::uuid, 'Culto Solene', 'culto', '2026-12-20T20:00:00.000Z', '2026-12-20T22:00:00.000Z', 'Templo principal', '', 'Pb. George Alves', 'Ir. Ana Dupont', 'Ir. Fernando', '2 Corintios 13', 'CULTO DE NATAL', 'scheduled'),
    ('2c41deb3-452b-4c3d-b0a6-29d92c8de467'::uuid, 'Escola Biblica', 'escola-biblica', '2026-12-20T12:30:00.000Z', '2026-12-20T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('da8de1d3-c18d-4b61-b0e0-e468b7bc62b7'::uuid, 'Livre', 'geral', '2026-12-22T22:30:00.000Z', '2026-12-23T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('7d34d4f6-3ba7-4d47-9810-e584b0326a9d'::uuid, 'Culto de Louvor', 'culto', '2026-12-24T22:30:00.000Z', '2026-12-25T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('51e28815-7893-49aa-8445-b3cbb967c1ff'::uuid, 'Culto Solene', 'culto', '2026-12-27T20:00:00.000Z', '2026-12-27T22:00:00.000Z', 'Templo principal', '', 'Pr. Augusto Lopes', 'Ir. Lisiane Flavia Lopes', 'Ir. Leandro', '', '', 'scheduled'),
    ('3e0f5aac-4c07-4d71-8305-47c84be1f1a0'::uuid, 'Escola Biblica', 'escola-biblica', '2026-12-27T12:30:00.000Z', '2026-12-27T14:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', '', 'scheduled'),
    ('7f6c89a5-2cec-46a7-b048-8bad2e49536e'::uuid, 'Livre', 'geral', '2026-12-29T22:30:00.000Z', '2026-12-30T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'free'),
    ('1d6d4576-da9c-4974-ae13-bb535a7fe7fa'::uuid, 'Culto de Louvor', 'culto', '2026-12-31T22:30:00.000Z', '2027-01-01T00:00:00.000Z', 'Templo principal', '', '', '', '', '', '', 'scheduled'),
    ('d5f99d06-4908-4eb8-b7e3-69aa7879d643'::uuid, 'Escola Biblica de Ferias', 'escola-biblica', '2026-07-25T18:00:00.000Z', '2026-07-25T21:00:00.000Z', 'Templo principal', '', '', 'DEPARTAMENTO INFANTIL', '', '', 'EBF', 'scheduled'),
    ('faebb5a5-e1c8-49ca-9c60-e39fee864435'::uuid, 'Culto dos VAROES', 'culto', '2026-08-15T22:30:00.000Z', '2026-08-16T00:00:00.000Z', 'Templo principal', '', '', 'Diac. Adeildo Natalicio', '', '', 'CULTO DOS VAROES', 'scheduled'),
    ('623bd3c6-c1e6-44ac-83f8-87c3e9f8a25a'::uuid, 'Culto da FAMILIA', 'culto', '2026-08-29T22:30:00.000Z', '2026-08-30T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', 'CULTO DA FAMILIA', 'scheduled'),
    ('df12dbbc-1732-47fa-bd04-70f5ecff1904'::uuid, 'CULTO UFBB', 'culto', '2026-10-17T22:30:00.000Z', '2026-10-18T00:00:00.000Z', 'Templo principal', '', '', 'UFBB', '', '', 'CULTO PARA MULHERES', 'scheduled'),
    ('a2ce050c-5179-4104-8dcc-e9f58cc1f0c6'::uuid, 'Culto dos VAROES', 'culto', '2026-11-07T22:30:00.000Z', '2026-11-08T00:00:00.000Z', 'Templo principal', '', '', 'Diac. Adeildo Natalicio', '', '', 'CULTO DOS VAROES', 'scheduled'),
    ('37496240-3821-48a0-bc2c-97abfc8b92f6'::uuid, 'CULTO DE NATAL', 'culto', '2026-12-20T22:00:00.000Z', '2026-12-21T00:00:00.000Z', 'Templo principal', '', '', 'Pr. Augusto Lopes', '', '', 'CULTO E CEIA DE NATAL', 'scheduled'),
    ('25f4cc42-097e-403f-9261-5502a348ad19'::uuid, 'CULTO ESPECIAL DE AGRADECIMENTO', 'culto', '2026-12-27T20:00:00.000Z', '2026-12-27T22:00:00.000Z', 'Templo principal', '', '', '', '', '', 'CULTO ESPECIAL DE AGRADECIMENTO', 'scheduled')
)
insert into public.schedule_items as si
  (id, title, ministry, starts_at, ends_at, location, summary,
   preacher, director, sound_team, passage, occasion_label, status, featured)
select
  ss.id,
  ss.title,
  ss.ministry,
  ss.starts_at,
  ss.ends_at,
  ss.location,
  ss.summary,
  ss.preacher,
  ss.director,
  ss.sound_team,
  ss.passage,
  ss.occasion_label,
  ss.status,
  false
from schedule_seed ss
on conflict (starts_at, title) do update set
  ministry = excluded.ministry,
  ends_at = excluded.ends_at,
  location = excluded.location,
  summary = excluded.summary,
  preacher = excluded.preacher,
  director = excluded.director,
  sound_team = excluded.sound_team,
  passage = excluded.passage,
  occasion_label = excluded.occasion_label,
  status = excluded.status
where si.ministry is distinct from excluded.ministry
   or si.ends_at is distinct from excluded.ends_at
   or si.location is distinct from excluded.location
   or si.summary is distinct from excluded.summary
   or si.preacher is distinct from excluded.preacher
   or si.director is distinct from excluded.director
   or si.sound_team is distinct from excluded.sound_team
   or si.passage is distinct from excluded.passage
   or si.occasion_label is distinct from excluded.occasion_label
   or si.status is distinct from excluded.status;

with volunteer_seed (id, name, role, sort_order) as (
  values
    ('ee3d3fd0-1c94-4c3a-92b8-4d5617d0351d'::uuid, 'Pr. Augusto Lopes', 'geral', 10),
    ('91d7a816-fb0c-4ee1-ba5a-39c0ac33c06c'::uuid, 'Pb. George Alves', 'geral', 20),
    ('c6e79461-c9c9-4ce2-b60b-36aca2366584'::uuid, 'Sem. Gediael Kallebe', 'geral', 30),
    ('3a250ac2-5972-4a86-9513-4a3b36b86c3a'::uuid, 'Sem. Ruth Alves', 'geral', 40),
    ('449dcf57-e4c8-4d1e-b12b-552b668dbe41'::uuid, 'Diac. Adeildo Natalicio', 'geral', 50),
    ('280c4ab1-9e23-42e0-b923-106b8f569aa5'::uuid, 'Diac. Aparecido Regino', 'geral', 60),
    ('c7669f2d-d24d-4cb9-8675-6cc54c8d8fe7'::uuid, 'Diac. Graca Lira', 'geral', 70),
    ('d2db0c80-331e-4e36-8cef-abeaa7844e5a'::uuid, 'Diac. Juliana Goberto', 'geral', 80),
    ('2b086766-8bfa-4340-b485-58366a1ecf52'::uuid, 'Diac. Luciano', 'geral', 90),
    ('df44726f-e4f2-4b41-94c7-9232705e0409'::uuid, 'Diac. Salete de Kassia', 'geral', 100),
    ('56c03512-7fb7-4d44-b9ee-a093c92e9b66'::uuid, 'Diac. Simone Oliveira', 'geral', 110),
    ('21a0e581-e365-4ac0-9ad5-37f05fb5a2db'::uuid, 'Ir. Ana Amelia', 'geral', 120),
    ('08b8f74f-23bd-48b6-991c-e991ac961d69'::uuid, 'Ir. Ana Claudia', 'geral', 130),
    ('026e5625-7d72-45ef-b340-28e1e1a36041'::uuid, 'Ir. Ana Dupont', 'geral', 140),
    ('2166af37-787a-4f7f-a1f9-a4404c852054'::uuid, 'Ir. Brainer', 'som', 150),
    ('2f75b8f0-3c6d-44d7-8cae-d247ae8cb904'::uuid, 'Ir. Dilma Martins', 'geral', 160),
    ('7cee5c53-26bc-41b5-ad65-fc6bcdde651c'::uuid, 'Ir. Edjane', 'geral', 170),
    ('2c1ac7aa-89c9-4630-be27-ec12cbf49347'::uuid, 'Ir. Fabiana', 'geral', 180),
    ('e2af722a-0ff1-43f8-970c-c2114dad4315'::uuid, 'Ir. Fernando', 'som', 190),
    ('44e21402-da69-491a-85ab-c522f4584fe5'::uuid, 'Ir. Gilmar Fonseca', 'geral', 200),
    ('8f1bfa80-bc00-4618-b1c6-23bc8dfb7860'::uuid, 'Ir. Leandro', 'som', 210),
    ('339a77f2-c25f-441f-9075-b8c2af21a0bc'::uuid, 'Ir. Lisiane Flavia Lopes', 'geral', 220),
    ('393c8f9e-9320-4070-91da-f786a27c2999'::uuid, 'Ir. Miguel', 'som', 230),
    ('eda63f8f-26fd-4066-8631-b82e430b1410'::uuid, 'Ir. Naim', 'geral', 240),
    ('340c185b-a57d-4abe-8533-b723db05c562'::uuid, 'ADOLESCENTES', 'geral', 250),
    ('e89aeee0-103b-493e-a6b1-ee8e7e0d342e'::uuid, 'Convidado', 'geral', 260),
    ('fe3156c5-d652-44d6-b19d-82b437353a53'::uuid, 'DEPARTAMENTO INFANTIL', 'geral', 270),
    ('5b35e199-2260-4fc8-a18c-97821658a1af'::uuid, 'GRUPO DE LOUVOR', 'geral', 280),
    ('94f1c1b1-c25c-4bce-a100-0069d2d10ea3'::uuid, 'UFBB', 'geral', 290),
    ('de7012b5-be82-4a86-b4ad-53c881113f5b'::uuid, 'VAROES', 'geral', 300)
)
insert into public.volunteers as v (id, name, role, sort_order)
select vs.id, vs.name, vs.role, vs.sort_order
from volunteer_seed vs
on conflict ((lower(name))) do update set
  role = excluded.role,
  sort_order = excluded.sort_order
where v.role is distinct from excluded.role
   or v.sort_order is distinct from excluded.sort_order;
-- END SEED --------------------------------------------------------------------

commit;
