-- Initial schema baseline (captured 2026-05-04 from supabase/schema.sql).
-- This migration is the canonical starting state of the database.
-- All future changes MUST be added as new migrations via:
--   npx supabase migration new <name>
-- DO NOT edit this file once it has been applied to any environment.

-- =============================================================================
-- 2. Extensions
-- =============================================================================

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;


-- =============================================================================
-- 3. Enum types
-- =============================================================================

create type public.admin_role as enum ('owner', 'editor');
create type public.announcement_category as enum ('geral', 'evento', 'juventude', 'oracao');
create type public.announcement_status as enum ('draft', 'scheduled', 'published', 'archived');
create type public.schedule_status as enum ('scheduled', 'suspended', 'free');
create type public.prayer_status as enum ('novo', 'em_oracao', 'concluido');
create type public.marital_status as enum ('solteiro', 'casado', 'viuvo', 'divorciado', 'uniao_estavel');
create type public.gender as enum ('masculino', 'feminino', 'outro');
create type public.membership_status as enum ('ativo', 'inativo', 'transferido', 'falecido');
create type public.church_role as enum (
  'membro_comum', 'presbitero', 'diacono',
  'conselho_fiscal', 'tesoureiro', 'secretario',
  'pastor', 'pastor_auxiliar'
);
create type public.relationship_type as enum (
  'conjuge', 'pai', 'mae', 'filho', 'irmao',
  'avo', 'neto', 'tio', 'sobrinho', 'responsavel'
);


-- =============================================================================
-- 4. Tables
-- =============================================================================

-- 4.1 Auth + admin --------------------------------------------------------

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role public.admin_role not null,
  created_at timestamptz not null default now()
);

create table public.admin_rate_limit_buckets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  created_at timestamptz not null default now()
);

-- 4.2 Institutional content ----------------------------------------------

create table public.church_profile (
  id text primary key default 'main' check (id = 'main'),
  name text not null default '',
  short_name text not null default '',
  tagline text not null default '',
  city text not null default '',
  pastor_name text not null default '',
  address text not null default '',
  email text not null default '',
  whatsapp text not null default '',
  instagram_url text not null default '',
  youtube_url text not null default '',
  maps_url text not null default '',
  hero_verse text not null default '',
  mission text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ministries (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  summary text not null default '',
  meeting_time text not null default '',
  contact text not null default '',
  color text not null default '#0f766e',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create table public.recurring_meetings (
  id uuid primary key default gen_random_uuid(),
  profile_id text not null default 'main' references public.church_profile(id) on delete cascade,
  title text not null,
  weekday smallint not null check (weekday between 0 and 6),
  starts_at time not null,
  ends_at time not null,
  description text not null default '',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recurring_meeting_time_order check (ends_at > starts_at)
);

create table public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  summary text not null,
  category public.announcement_category not null,
  published_at timestamptz not null default now(),
  pinned boolean not null default false,
  cta_label text not null default '',
  cta_url text not null default '',
  status public.announcement_status not null default 'published',
  expires_at timestamptz null,
  image_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

-- 4.3 Members + family ----------------------------------------------------

create table public.households (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  head_member_id uuid null,
  address_zip text not null default '',
  address_street text not null default '',
  address_number text not null default '',
  address_complement text not null default '',
  address_neighborhood text not null default '',
  address_city text not null default '',
  address_state text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create table public.members (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  preferred_name text not null default '',
  birth_date date null,
  marital_status public.marital_status null,
  gender public.gender null,
  photo_url text not null default '',
  email text not null default '',
  phone text not null default '',
  whatsapp text not null default '',
  cpf text null,
  rg text not null default '',
  rg_issuer text not null default '',
  profession text not null default '',
  address_zip text not null default '',
  address_street text not null default '',
  address_number text not null default '',
  address_complement text not null default '',
  address_neighborhood text not null default '',
  address_city text not null default '',
  address_state text not null default '',
  household_id uuid null references public.households(id) on delete set null,
  church_role public.church_role not null default 'membro_comum',
  membership_status public.membership_status not null default 'ativo',
  joined_at date null,
  baptism_date date null,
  baptism_location text not null default '',
  transferred_from text not null default '',
  emergency_contact_name text not null default '',
  emergency_contact_phone text not null default '',
  prayer_topics text[] not null default '{}',
  spiritual_gifts text[] not null default '{}',
  allergies text not null default '',
  medical_notes text not null default '',
  consent_medical_data_at timestamptz null,
  is_volunteer boolean not null default false,
  volunteer_ministries text[] not null default '{}',
  volunteer_unavailable_dates date[] not null default '{}',
  volunteer_notes text not null default '',
  notes text not null default '',
  consent_given_at timestamptz null,
  consent_version text not null default '',
  public_directory boolean not null default false,
  data_retention_until date null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  constraint members_cpf_format check (cpf ~ '^[0-9]{11}$' or cpf is null)
);

alter table public.households
  add constraint households_head_member_fk
  foreign key (head_member_id) references public.members(id) on delete set null;

create table public.member_relationships (
  id uuid primary key default gen_random_uuid(),
  from_member_id uuid not null references public.members(id) on delete cascade,
  to_member_id uuid not null references public.members(id) on delete cascade,
  type public.relationship_type not null,
  start_date date null,
  end_date date null,
  created_at timestamptz not null default now(),
  constraint different_members check (from_member_id <> to_member_id),
  constraint unique_active_relationship unique (from_member_id, to_member_id, type, start_date)
);

-- 4.4 Schedule ------------------------------------------------------------

create table public.schedule_items (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  ministry text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  location text not null,
  summary text not null,
  preacher text not null default '',
  director text not null default '',
  sound_team text not null default '',
  passage text not null default '',
  occasion_label text not null default '',
  status public.schedule_status not null default 'scheduled',
  featured boolean not null default false,
  series_id uuid null,
  preacher_member_id uuid null references public.members(id) on delete set null,
  director_member_id uuid null references public.members(id) on delete set null,
  sound_member_id uuid null references public.members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  constraint schedule_time_order check (ends_at > starts_at),
  constraint schedule_items_starts_at_title_unique unique (starts_at, title)
);

-- 4.5 Prayer requests + rate limit ---------------------------------------

create table public.prayer_requests (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contact text not null default '',
  message text not null,
  status public.prayer_status not null default 'novo',
  pastoral_notes text not null default '',
  assigned_to uuid null references public.admin_users(user_id) on delete set null,
  seen_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create table public.prayer_request_rate_limits (
  id uuid primary key default gen_random_uuid(),
  ip_hash text not null,
  created_at timestamptz not null default now()
);

-- 4.6 Audit log -----------------------------------------------------------

create table public.content_audit_log (
  id uuid primary key default gen_random_uuid(),
  table_name text not null,
  row_id text not null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  changed_by uuid,
  changed_at timestamptz not null default now(),
  old_row jsonb,
  new_row jsonb
);


-- =============================================================================
-- 5. Functions
-- =============================================================================

-- 5.1 Helper triggers -----------------------------------------------------

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.log_content_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_row jsonb;
  target_id text;
begin
  if tg_op = 'DELETE' then
    target_row = to_jsonb(old);
    target_id = old.id::text;
  else
    target_row = to_jsonb(new);
    target_id = new.id::text;
  end if;

  insert into public.content_audit_log (
    table_name, row_id, action, changed_by, old_row, new_row
  ) values (
    tg_table_name,
    target_id,
    tg_op,
    auth.uid(),
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then target_row else null end
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

-- 5.2 Authorization helpers ----------------------------------------------

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_users where user_id = auth.uid());
$$;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid() and role = 'owner'
  );
$$;

-- 5.3 Admin listing -------------------------------------------------------

create or replace function public.list_admins()
returns table (
  user_id uuid,
  email text,
  display_name text,
  role public.admin_role,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado: apenas admins podem listar admins.';
  end if;

  return query
    select
      a.user_id,
      u.email::text,
      coalesce(u.raw_user_meta_data->>'name', '')::text as display_name,
      a.role,
      a.created_at
    from public.admin_users a
    inner join auth.users u on u.id = a.user_id;
end;
$$;

-- 5.4 Rate limit ---------------------------------------------------------

create or replace function public.check_admin_rate_limit(p_action text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  recent_count int;
begin
  if auth.uid() is null then
    return false;
  end if;

  select count(*) into recent_count
  from public.admin_rate_limit_buckets
  where user_id = auth.uid()
    and action = p_action
    and created_at > now() - interval '1 minute';

  if recent_count >= 30 then
    return false;
  end if;

  insert into public.admin_rate_limit_buckets (user_id, action)
  values (auth.uid(), p_action);

  return true;
end;
$$;

-- 5.5 Archive / restore RPCs ---------------------------------------------

create or replace function public.archive_member(p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Acesso negado.'; end if;
  if not public.check_admin_rate_limit('archive_member') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.members set deleted_at = now() where id = p_id and deleted_at is null;
end; $$;

create or replace function public.restore_member(p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Acesso negado.'; end if;
  if not public.check_admin_rate_limit('restore_member') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.members set deleted_at = null where id = p_id;
end; $$;

create or replace function public.archive_announcement(p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Acesso negado.'; end if;
  if not public.check_admin_rate_limit('archive_announcement') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.announcements set deleted_at = now() where id = p_id and deleted_at is null;
end; $$;

create or replace function public.restore_announcement(p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Acesso negado.'; end if;
  if not public.check_admin_rate_limit('restore_announcement') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.announcements set deleted_at = null where id = p_id;
end; $$;

create or replace function public.archive_schedule_item(p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Acesso negado.'; end if;
  if not public.check_admin_rate_limit('archive_schedule_item') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.schedule_items set deleted_at = now() where id = p_id and deleted_at is null;
end; $$;

create or replace function public.restore_schedule_item(p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Acesso negado.'; end if;
  if not public.check_admin_rate_limit('restore_schedule_item') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.schedule_items set deleted_at = null where id = p_id;
end; $$;

create or replace function public.archive_prayer_request(p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Acesso negado.'; end if;
  if not public.check_admin_rate_limit('archive_prayer_request') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.prayer_requests set deleted_at = now() where id = p_id and deleted_at is null;
end; $$;

create or replace function public.restore_prayer_request(p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Acesso negado.'; end if;
  if not public.check_admin_rate_limit('restore_prayer_request') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.prayer_requests set deleted_at = null where id = p_id;
end; $$;

create or replace function public.archive_ministry(p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Acesso negado.'; end if;
  if not public.check_admin_rate_limit('archive_ministry') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.ministries set deleted_at = now() where id = p_id and deleted_at is null;
end; $$;

create or replace function public.restore_ministry(p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Acesso negado.'; end if;
  if not public.check_admin_rate_limit('restore_ministry') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;
  update public.ministries set deleted_at = null where id = p_id;
end; $$;

-- 5.6 Audit revert -------------------------------------------------------

create or replace function public.revert_audit_entry(entry_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  entry public.content_audit_log%rowtype;
  allowed_tables text[] := array[
    'announcements', 'schedule_items', 'prayer_requests',
    'church_profile', 'ministries', 'recurring_meetings',
    'members', 'households', 'member_relationships'
  ];
  cols text;
  vals text;
  set_clause text;
  payload jsonb;
begin
  if not public.is_admin() then
    raise exception 'Acesso negado: apenas admins podem reverter alteracoes.';
  end if;

  select * into entry from public.content_audit_log where id = entry_id;
  if not found then
    raise exception 'Entrada de audit log nao encontrada: %', entry_id;
  end if;

  if not (entry.table_name = any(allowed_tables)) then
    raise exception 'Tabela nao autorizada para revert: %', entry.table_name;
  end if;

  if entry.action = 'INSERT' then
    execute format('delete from public.%I where id = $1', entry.table_name)
      using entry.row_id;
  elsif entry.action = 'UPDATE' then
    payload := entry.old_row;
    if payload is null then
      raise exception 'old_row ausente em UPDATE; impossivel reverter.';
    end if;
    select string_agg(
      format('%I = (jsonb_populate_record(null::public.%I, $1)).%I', key, entry.table_name, key),
      ', '
    )
      into set_clause
      from jsonb_object_keys(payload) as key
      where key <> 'id';
    if set_clause is null then return; end if;
    execute format('update public.%I set %s where id = $2', entry.table_name, set_clause)
      using payload, entry.row_id;
  elsif entry.action = 'DELETE' then
    payload := entry.old_row;
    if payload is null then
      raise exception 'old_row ausente em DELETE; impossivel reverter.';
    end if;
    select
      string_agg(format('%I', key), ', '),
      string_agg(format('(jsonb_populate_record(null::public.%I, $1)).%I', entry.table_name, key), ', ')
      into cols, vals
      from jsonb_object_keys(payload) as key;
    execute format('insert into public.%I (%s) values (%s)', entry.table_name, cols, vals)
      using payload;
  else
    raise exception 'Acao desconhecida: %', entry.action;
  end if;
end;
$$;

-- 5.7 Members helpers ----------------------------------------------------

create or replace function public.find_member_duplicates(
  p_full_name text,
  p_cpf text,
  p_email text,
  p_phone text
)
returns table (
  member_id uuid,
  full_name text,
  score numeric,
  match_reason text
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  phone_digits text := regexp_replace(coalesce(p_phone, ''), '\D+', '', 'g');
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;

  return query
  with candidates as (
    select
      m.id as member_id,
      m.full_name as full_name,
      case
        when p_cpf is not null and p_cpf <> '' and m.cpf = p_cpf then 1.0
        when p_email <> '' and lower(m.email) = lower(p_email) then 0.9
        when phone_digits <> '' and regexp_replace(coalesce(m.phone, ''), '\D+', '', 'g') = phone_digits then 0.85
        when phone_digits <> '' and regexp_replace(coalesce(m.whatsapp, ''), '\D+', '', 'g') = phone_digits then 0.85
        when similarity(m.full_name, coalesce(p_full_name, '')) > 0.7
          then similarity(m.full_name, p_full_name)::numeric
        else 0
      end as score,
      case
        when p_cpf is not null and p_cpf <> '' and m.cpf = p_cpf then 'cpf_match'
        when p_email <> '' and lower(m.email) = lower(p_email) then 'email_match'
        when phone_digits <> '' and regexp_replace(coalesce(m.phone, ''), '\D+', '', 'g') = phone_digits then 'phone_match'
        when phone_digits <> '' and regexp_replace(coalesce(m.whatsapp, ''), '\D+', '', 'g') = phone_digits then 'phone_match'
        when similarity(m.full_name, coalesce(p_full_name, '')) > 0.7 then 'name_similar'
        else null
      end as match_reason
    from public.members m
    where m.deleted_at is null
  )
  select c.member_id, c.full_name, c.score, c.match_reason
  from candidates c
  where c.score > 0
  order by c.score desc
  limit 5;
end;
$$;

create or replace function public.anonymize_member(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso negado.';
  end if;
  if not public.check_admin_rate_limit('anonymize_member') then
    raise exception 'Limite de operacoes destrutivas excedido. Aguarde um instante.';
  end if;

  update public.members
  set
    full_name = '[anonimizado]',
    preferred_name = '',
    birth_date = null,
    marital_status = null,
    gender = null,
    photo_url = '',
    email = '',
    phone = '',
    whatsapp = '',
    cpf = null,
    rg = '',
    rg_issuer = '',
    profession = '',
    address_zip = '',
    address_street = '',
    address_number = '',
    address_complement = '',
    address_neighborhood = '',
    address_city = '',
    address_state = '',
    baptism_location = '',
    transferred_from = '',
    emergency_contact_name = '',
    emergency_contact_phone = '',
    prayer_topics = '{}',
    spiritual_gifts = '{}',
    allergies = '',
    medical_notes = '',
    consent_medical_data_at = null,
    volunteer_notes = '',
    notes = '[anonimizado]',
    consent_given_at = null,
    consent_version = '',
    public_directory = false,
    deleted_at = coalesce(deleted_at, now())
  where id = p_id;
end;
$$;

-- 5.8 Member relationships reverse mirror --------------------------------

create or replace function public.create_reverse_relationship()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  reverse_type public.relationship_type;
  to_gender public.gender;
begin
  if pg_trigger_depth() > 1 then return new; end if;
  case new.type
    when 'pai' then reverse_type := 'filho';
    when 'mae' then reverse_type := 'filho';
    when 'avo' then reverse_type := 'neto';
    when 'tio' then reverse_type := 'sobrinho';
    when 'irmao' then reverse_type := 'irmao';
    when 'conjuge' then reverse_type := 'conjuge';
    when 'neto' then reverse_type := 'avo';
    when 'sobrinho' then reverse_type := 'tio';
    when 'filho' then
      select gender into to_gender from public.members where id = new.to_member_id;
      reverse_type := case
        when to_gender = 'feminino' then 'mae'::public.relationship_type
        else 'pai'::public.relationship_type
      end;
    else return new;
  end case;
  insert into public.member_relationships (from_member_id, to_member_id, type, start_date, end_date)
  values (new.to_member_id, new.from_member_id, reverse_type, new.start_date, new.end_date)
  on conflict (from_member_id, to_member_id, type, start_date) do nothing;
  return new;
end;
$$;

create or replace function public.delete_reverse_relationship()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  reverse_type public.relationship_type;
  to_gender public.gender;
begin
  if pg_trigger_depth() > 1 then return old; end if;
  case old.type
    when 'pai' then reverse_type := 'filho';
    when 'mae' then reverse_type := 'filho';
    when 'avo' then reverse_type := 'neto';
    when 'tio' then reverse_type := 'sobrinho';
    when 'irmao' then reverse_type := 'irmao';
    when 'conjuge' then reverse_type := 'conjuge';
    when 'neto' then reverse_type := 'avo';
    when 'sobrinho' then reverse_type := 'tio';
    when 'filho' then
      select gender into to_gender from public.members where id = old.to_member_id;
      reverse_type := case
        when to_gender = 'feminino' then 'mae'::public.relationship_type
        else 'pai'::public.relationship_type
      end;
    else return old;
  end case;
  delete from public.member_relationships
  where from_member_id = old.to_member_id
    and to_member_id = old.from_member_id
    and type = reverse_type
    and start_date is not distinct from old.start_date;
  return old;
end;
$$;


-- 5.9 Background maintenance --------------------------------------------

create or replace function public.purge_old_prayers()
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  affected int;
begin
  with purged as (
    update public.prayer_requests
    set deleted_at = now()
    where status = 'concluido'
      and updated_at < now() - interval '18 months'
      and deleted_at is null
    returning 1
  )
  select count(*) into affected from purged;
  return affected;
end;
$$;


-- =============================================================================
-- 6. Indexes
-- =============================================================================

-- 6.1 Schedule -----------------------------------------------------------
create index schedule_starts_at_idx on public.schedule_items (starts_at);
create index schedule_scheduled_starts_at_idx
  on public.schedule_items (starts_at) where status = 'scheduled';
create index schedule_ministry_idx on public.schedule_items (ministry);
create index schedule_series_id_idx on public.schedule_items (series_id);
create index schedule_items_active_idx
  on public.schedule_items (starts_at) where deleted_at is null;

-- 6.2 Announcements ------------------------------------------------------
create index announcements_pinned_published_at_idx
  on public.announcements (published_at desc) where pinned = true;
create index announcements_status_published_at_idx
  on public.announcements (status, published_at desc);
create index announcements_active_idx
  on public.announcements (published_at desc) where deleted_at is null;

-- 6.3 Prayer requests ----------------------------------------------------
create index prayer_requests_created_at_idx
  on public.prayer_requests (created_at desc);
create index prayer_requests_assigned_to_idx
  on public.prayer_requests (assigned_to) where assigned_to is not null;
create index prayer_requests_active_idx
  on public.prayer_requests (created_at desc) where deleted_at is null;
create index prayer_rate_limits_ip_created_at_idx
  on public.prayer_request_rate_limits (ip_hash, created_at desc);

-- 6.4 Ministries ---------------------------------------------------------
create index ministries_sort_order_idx on public.ministries (sort_order);
create index ministries_active_idx
  on public.ministries (sort_order) where deleted_at is null;

-- 6.5 Members + family ---------------------------------------------------
create unique index members_cpf_unique
  on public.members (cpf) where cpf is not null and deleted_at is null;
create index members_email_idx on public.members (email);
create index members_phone_idx on public.members (phone);
create index members_household_id_idx on public.members (household_id);
create index members_is_volunteer_idx
  on public.members (is_volunteer) where is_volunteer = true;
create index members_deleted_at_idx on public.members (deleted_at);
create index members_full_name_trgm_idx
  on public.members using gin (full_name gin_trgm_ops);
create index households_deleted_at_idx on public.households (deleted_at);
create index member_relationships_from_idx
  on public.member_relationships (from_member_id);
create index member_relationships_to_idx
  on public.member_relationships (to_member_id);

-- 6.6 Rate limit + audit ------------------------------------------------
create index admin_rate_limit_buckets_user_created_idx
  on public.admin_rate_limit_buckets (user_id, created_at desc);
create index recurring_meetings_sort_order_idx
  on public.recurring_meetings (sort_order);
create index recurring_meetings_weekday_idx
  on public.recurring_meetings (weekday);
create index content_audit_log_changed_at_idx
  on public.content_audit_log (changed_at desc);
create index content_audit_log_table_row_idx
  on public.content_audit_log (table_name, row_id, changed_at desc);


-- =============================================================================
-- 7. Triggers
-- =============================================================================

-- 7.1 updated_at touch ---------------------------------------------------
create trigger touch_announcements_updated_at
  before update on public.announcements
  for each row execute function public.touch_updated_at();
create trigger touch_schedule_items_updated_at
  before update on public.schedule_items
  for each row execute function public.touch_updated_at();
create trigger touch_prayer_requests_updated_at
  before update on public.prayer_requests
  for each row execute function public.touch_updated_at();
create trigger touch_members_updated_at
  before update on public.members
  for each row execute function public.touch_updated_at();
create trigger touch_households_updated_at
  before update on public.households
  for each row execute function public.touch_updated_at();
create trigger touch_church_profile_updated_at
  before update on public.church_profile
  for each row execute function public.touch_updated_at();
create trigger touch_ministries_updated_at
  before update on public.ministries
  for each row execute function public.touch_updated_at();
create trigger touch_recurring_meetings_updated_at
  before update on public.recurring_meetings
  for each row execute function public.touch_updated_at();

-- 7.2 Audit log ---------------------------------------------------------
create trigger audit_announcements
  after insert or update or delete on public.announcements
  for each row execute function public.log_content_audit();
create trigger audit_schedule_items
  after insert or update or delete on public.schedule_items
  for each row execute function public.log_content_audit();
create trigger audit_prayer_requests
  after insert or update or delete on public.prayer_requests
  for each row execute function public.log_content_audit();
create trigger audit_members
  after insert or update or delete on public.members
  for each row execute function public.log_content_audit();
create trigger audit_households
  after insert or update or delete on public.households
  for each row execute function public.log_content_audit();
create trigger audit_member_relationships
  after insert or update or delete on public.member_relationships
  for each row execute function public.log_content_audit();
create trigger audit_church_profile
  after insert or update or delete on public.church_profile
  for each row execute function public.log_content_audit();
create trigger audit_ministries
  after insert or update or delete on public.ministries
  for each row execute function public.log_content_audit();
create trigger audit_recurring_meetings
  after insert or update or delete on public.recurring_meetings
  for each row execute function public.log_content_audit();

-- 7.3 Member relationships reverse mirror -------------------------------
create trigger member_relationships_reverse_insert
  after insert on public.member_relationships
  for each row execute function public.create_reverse_relationship();

create trigger member_relationships_reverse_delete
  after delete on public.member_relationships
  for each row execute function public.delete_reverse_relationship();


-- =============================================================================
-- 8. Row Level Security and policies
-- =============================================================================

-- Restore Supabase default base grants. drop schema public cascade revokes
-- everything; without these grants the client gets `permission denied` BEFORE
-- RLS even has a chance to filter. RLS narrows what each role can see; the
-- grants below give the base permission for RLS to apply on top.
grant select on all tables in schema public to anon, authenticated;
grant insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
grant execute on all functions in schema public to anon, authenticated;

alter default privileges in schema public
  grant select on tables to anon, authenticated;
alter default privileges in schema public
  grant insert, update, delete on tables to authenticated;
alter default privileges in schema public
  grant execute on functions to anon, authenticated;

alter table public.admin_users enable row level security;
alter table public.admin_rate_limit_buckets enable row level security;
alter table public.announcements enable row level security;
alter table public.schedule_items enable row level security;
alter table public.members enable row level security;
alter table public.households enable row level security;
alter table public.member_relationships enable row level security;
alter table public.prayer_requests enable row level security;
alter table public.prayer_request_rate_limits enable row level security;
alter table public.content_audit_log enable row level security;
alter table public.church_profile enable row level security;
alter table public.ministries enable row level security;
alter table public.recurring_meetings enable row level security;

-- 8.1 admin_users -------------------------------------------------------
create policy "admins can read own admin row"
  on public.admin_users for select to authenticated
  using (user_id = auth.uid());
create policy "owners can manage admin users"
  on public.admin_users for all to authenticated
  using (public.is_owner()) with check (public.is_owner());

-- 8.2 announcements -----------------------------------------------------
create policy "public can read announcements"
  on public.announcements for select to anon, authenticated
  using (deleted_at is null);
create policy "admins can read all announcements"
  on public.announcements for select to authenticated
  using (public.is_admin());
create policy "admins can insert announcements"
  on public.announcements for insert to authenticated
  with check (public.is_admin());
create policy "admins can update announcements"
  on public.announcements for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- 8.3 schedule_items ----------------------------------------------------
create policy "public can read schedule"
  on public.schedule_items for select to anon, authenticated
  using (deleted_at is null);
create policy "admins can read all schedule"
  on public.schedule_items for select to authenticated
  using (public.is_admin());
create policy "admins can insert schedule"
  on public.schedule_items for insert to authenticated
  with check (public.is_admin());
create policy "admins can update schedule"
  on public.schedule_items for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- 8.4 members + family --------------------------------------------------
create policy "public can read public members"
  on public.members for select to anon, authenticated
  using (deleted_at is null and public_directory = true);
create policy "admins can read all members"
  on public.members for select to authenticated
  using (public.is_admin());
create policy "admins can insert members"
  on public.members for insert to authenticated
  with check (public.is_admin());
create policy "admins can update members"
  on public.members for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "admins can read households"
  on public.households for select to authenticated
  using (public.is_admin());
create policy "admins can insert households"
  on public.households for insert to authenticated
  with check (public.is_admin());
create policy "admins can update households"
  on public.households for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "admins can read member relationships"
  on public.member_relationships for select to authenticated
  using (public.is_admin());
create policy "admins can insert member relationships"
  on public.member_relationships for insert to authenticated
  with check (public.is_admin());
create policy "admins can update member relationships"
  on public.member_relationships for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy "admins can delete member relationships"
  on public.member_relationships for delete to authenticated
  using (public.is_admin());

-- 8.5 prayer requests ---------------------------------------------------
create policy "admins can read prayer requests"
  on public.prayer_requests for select to authenticated
  using (public.is_admin());
create policy "admins can insert prayer requests"
  on public.prayer_requests for insert to authenticated
  with check (public.is_admin());
create policy "admins can update prayer requests"
  on public.prayer_requests for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- 8.6 audit log ---------------------------------------------------------
create policy "admins can read audit log"
  on public.content_audit_log for select to authenticated
  using (public.is_admin());

-- 8.7 institutional content --------------------------------------------
create policy "public can read church profile"
  on public.church_profile for select to anon, authenticated
  using (true);
create policy "admins can write church profile"
  on public.church_profile for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "public can read ministries"
  on public.ministries for select to anon, authenticated
  using (deleted_at is null);
create policy "admins can read all ministries"
  on public.ministries for select to authenticated
  using (public.is_admin());
create policy "admins can insert ministries"
  on public.ministries for insert to authenticated
  with check (public.is_admin());
create policy "admins can update ministries"
  on public.ministries for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "public can read recurring meetings"
  on public.recurring_meetings for select to anon, authenticated
  using (true);
create policy "admins can write recurring meetings"
  on public.recurring_meetings for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- admin_rate_limit_buckets and prayer_request_rate_limits intentionally
-- have NO policies. RLS is enabled with no policies, so direct access from
-- any client is denied; only SECURITY DEFINER RPCs and service_role can
-- read or write.


-- =============================================================================
-- 9. Legacy compatibility view
-- =============================================================================
-- `volunteers` was a table in the legacy schema; now it is a read-only view
-- derived from `members` where is_volunteer = true. The frontend adapter
-- still queries `volunteers` for backwards compatibility.

create view public.volunteers as
select
  m.id,
  m.full_name as name,
  case
    when array_length(m.volunteer_ministries, 1) > 0 then m.volunteer_ministries[1]
    else 'geral'
  end as role,
  0 as sort_order,
  coalesce(nullif(m.whatsapp, ''), nullif(m.phone, ''), m.email) as contact,
  m.photo_url,
  m.volunteer_ministries as ministries,
  m.volunteer_unavailable_dates as unavailable_dates,
  m.volunteer_notes as notes,
  m.created_at,
  m.updated_at
from public.members m
where m.is_volunteer = true and m.deleted_at is null;


-- =============================================================================
-- 10. Institutional seeds (church profile + admin owners)
-- =============================================================================
-- Seed the church profile (idempotent).

insert into public.church_profile (
  id, name, short_name, tagline, city, pastor_name, address, email, whatsapp,
  instagram_url, youtube_url, maps_url, hero_verse, mission
) values (
  'main',
  '4a Igreja Batista Independente Betel',
  '4a Betel',
  'Uma igreja para servir a cidade com Palavra, comunhao e cuidado.',
  'Caruaru, PE',
  'Pr. Samuel Costa',
  '478 Rua Jose Victor de Albuquerque',
  '4ibibetel@gmail.com',
  '+55 81 98122-0651',
  'https://www.instagram.com/4igrejabatista/',
  'https://www.youtube.com/@4aibibetel864',
  'https://maps.google.com/?q=Av.+Central,+420+-+Centro',
  'Assim brilhe a luz de voces diante dos homens, para que vejam as suas boas obras e glorifiquem o Pai de voces que esta nos ceus. - Mateus 5.16',
  'Cultivar discipulos de Jesus que servem com excelencia, oracao e acolhimento.'
) on conflict (id) do nothing;

-- Seed the initial admin owners by email lookup. If an auth.user with the
-- listed email does not exist yet, the row is silently skipped — create the
-- account in Supabase Auth first, then re-run this block.

insert into public.admin_users (user_id, role)
select id, 'owner'::public.admin_role
from auth.users
where email in ('gediael54@gmail.com', 'agtlislopes@gmail.com')
on conflict (user_id) do nothing;


-- =============================================================================
-- 11. Schedule + members seed (auto-generated from supabase/sources/*.xlsx)
-- =============================================================================
-- Run `npm run seed:schedule` to regenerate everything between the SEED markers
-- below. Do not edit by hand: changes will be overwritten.

